'use strict';
const STRATEGY_VIEW={
 button(label,action,data='',locked=false,cost=0,kind='outline'){return `<button class="${kind}-button" data-match="${action}" ${data} ${locked?'data-locked="true" disabled':''} ${cost?`data-cost="${cost}"`:''}>${label}</button>`;},
 countdown(end,now){return `<span data-strategy-end="${end}">${Math.max(0,Math.ceil((end-now)/1000))}s</span>`;},
 render(c){const r=c.room,p=r.players.find(p=>p.id===c.self);if(!p)return;const ev=STRATEGY.event(r),finished=r.status==='finished';
  const signature=JSON.stringify({...r,now:0,players:r.players.map(p=>({...p,money:0,incomeRemainder:0}))})+c.view+c.rival+c.plot+c.selectedNode+c.paused+c.speed+c.error+ev.cycle+ev.active+JSON.stringify(r.players.map(q=>[q.jamUntil>r.now,q.shieldUntil>r.now,q.immuneUntil>r.now,q.jamCooldown>r.now,Boolean(q.production&&q.production.end-r.now<5000||q.lastLaunch&&r.now-q.lastLaunch<5000)]))+Math.floor(Math.max(0,r.now-r.started)/STRATEGY.grace);
  if(signature===c.strategySignature&&c.root.querySelector('.strategy-shell')){this.live(c);return;}c.strategySignature=signature;
  const focus=document.activeElement?.dataset?.match?{...document.activeElement.dataset}:null;
  const rival=r.players.find(q=>q.id===c.rival&&q.id!==c.self),viewPlayer=rival||p,n=r.nodes.find(n=>n.countryId===c.selectedNode)||r.nodes[0],count=STRATEGY.owned(r,p.id).length,power=STRATEGY.power(p),winner=r.players.find(q=>q.id===r.winner);
  const milestones=[['First launch',p.satellites>=2],['3 connected regions',count>=3],['Six satellites',p.satellites>=6],['Orbital station',STRATEGY.level(p,'station')>0]];
  c.root.innerHTML=`<main class="strategy-shell match-shell"><header class="strategy-header"><div><p class="eyebrow">ORBIT PACT / ${c.mode==='solo'?'ENDLESS SOLO · '+c.difficulty.toUpperCase():'NETWORK DOMINANCE'}</p><h1>${finished?Utils.escape(winner?.name||'Company')+' wins!':Utils.escape(p.name)}</h1></div><div class="match-controls">${c.mode==='solo'?this.button(c.paused?'Resume':'Pause','pause')+this.button(c.speed+'×','speed'):`<div class="lobby-code"><small>LOBBY CODE</small><strong>${c.connection.code}</strong></div>${this.button('Copy code','copy')}`}${this.button('Menu','menu')}</div></header>
   <div class="strategy-resources"><div><small>FUNDS</small><strong id="strategyFunds">${Utils.money(p.money)}</strong></div><div><small>NETWORK / 5s</small><strong id="strategyIncome">+${Utils.money(STRATEGY.income(r,p))}</strong></div><div><small>SATELLITES</small><strong>${p.satellites} <small>· ${p.satellites-p.missions.length} free</small></strong></div><div><small>REGIONS</small><strong>${count} <small>/ ${p.satellites*2} capacity</small></strong></div><div><small>POWER</small><strong>${power.used} / ${power.supply}</strong></div></div>
   <div class="strategy-alert"><p id="matchError" class="match-error" role="status">${Utils.escape(c.error)}</p>${c.mode==='online'?this.button('Reconnect','retry'):''}</div>
   ${p.jamUntil>r.now?`<div class="signal-warning">Your network is disrupted for ${this.countdown(p.jamUntil,r.now)}. ${this.button('Restore with shield · €6,000','shield','',finished,6000,'primary')}</div>`:''}
   <div class="strategy-layout"><section class="strategy-main"><div class="scene-toolbar"><div class="segmented">${this.button('World network','view','data-view="world"',false,0,c.view==='world'?'primary':'outline')}${this.button('My spaceport','view','data-view="base"',false,0,c.view==='base'&&!rival?'primary':'outline')}</div><span>${c.mode==='solo'?'No time limit':`Hold ${STRATEGY.target}/${r.nodes.length} regions for 45 seconds`}</span></div>
   <div class="strategy-scene panel">${c.view==='base'?SPACEPORT_SCENE.render(viewPlayer,r.now,c.plot,!rival):'<svg id="strategyWorld" viewBox="0 0 900 490" aria-label="World network. Select a country or a network marker."></svg>'}</div>
   <div class="milestone-strip">${milestones.map(([title,done])=>`<span class="${done?'achieved':''}">${done?'✓':'○'} ${title}</span>`).join('')}</div>
   <div class="strategy-companies">${r.players.map(q=>{const owned=STRATEGY.owned(r,q.id).length;return `<button class="company-tile ${q.id===p.id?'you':''}" data-match="rival" data-target="${q.id}"><strong><i style="background:${c.color(q.id)}"></i>${Utils.escape(q.name)}</strong><span>${owned} regions · ${q.satellites} satellites</span><progress value="${owned}" max="${r.nodes.length}" aria-label="${Utils.escape(q.name)} regions"></progress>${q.dominanceSince!==null?`<small>${r.endless?'Network leader':`Dominance in ${this.countdown(q.dominanceSince+STRATEGY.hold,r.now)}`}</small>`:''}${q.shieldUntil>r.now?'<small>SHIELD ACTIVE</small>':q.jamUntil>r.now?'<small>SIGNAL DISRUPTED</small>':''}</button>`;}).join('')}</div>
   <section class="panel strategy-market"><div class="panel-heading"><h2>Mission control</h2><span>${p.missions.length} active</span></div><div class="active-missions">${p.missions.map(m=>`<div><strong>${Utils.escape(m.name)}</strong><span>${this.countdown(m.end,r.now)} · +${Utils.money(m.reward)}</span><progress value="${Math.max(0,r.now-(m.start||m.end-m.duration))}" max="${m.end-(m.start||m.end-m.duration)}" data-mission-start="${m.start||m.end-m.duration}" data-mission-end="${m.end}"></progress></div>`).join('')||'<p class="subtle">Your fleet is ready. Choose a contract below, or take the priority request.</p>'}</div>
   <div class="contract-cards">${r.offers.map(o=>`<article><small>${Utils.escape(Utils.country(o.countryId).properties.name)}</small><h3>${o.name}</h3><strong>+${Utils.money(Math.round(o.reward*(1+.1*Math.min(3,p.fleet.mapper)))-o.cost)}</strong><p>${Math.round(o.duration*(1-.1*STRATEGY.level(p,'lab'))/1000)}s · start ${Utils.money(o.cost)}</p>${this.button('Accept','accept',`data-id="${o.id}"`,finished||p.missions.length>=p.satellites,o.cost)}</article>`).join('')}</div></section>
   <section class="panel strategy-log"><h2>World activity</h2>${(r.log||[]).slice(0,6).map(l=>`<p><time>${Utils.time(Math.max(0,l.time-r.started))}</time>${Utils.escape(l.text)}</p>`).join('')}</section></section>
   <aside class="strategy-sidebar"><section class="panel strategy-inspector">${c.view==='base'?this.baseInspector(c,p,viewPlayer,Boolean(rival&&rival.id!==p.id),finished):this.nodeInspector(c,p,n,finished)}</section>
   <section class="panel priority-request"><p class="eyebrow">${ev.active?'PRIORITY REQUEST':'NEXT OPPORTUNITY'}</p><h2>${ev.name}</h2><p>${ev.active?`Accept within ${this.countdown(ev.end,r.now)}. One request per company.`:`A new request arrives in ${this.countdown(ev.end+45000,r.now)}.`}</p><strong>+${Utils.money(Math.round(ev.reward*(1+.1*Math.min(3,p.fleet.mapper)))-3000)} profit</strong>${this.button(p.lastEvent===ev.cycle?'Request accepted':'Deploy · €3,000','event','',finished||!ev.active||p.lastEvent===ev.cycle||p.missions.length>=p.satellites,3000,'primary')}</section>
   <section class="panel strategy-defense"><h2>Signal security</h2><p>${r.now-r.started<STRATEGY.grace?`Opening truce ends in ${this.countdown(r.started+STRATEGY.grace,r.now)}.`:'Shields block sabotage and new takeovers for 60 seconds. They immediately restore a disrupted signal.'}</p>${this.button(p.shieldUntil>r.now?'Shield active · '+this.countdown(p.shieldUntil,r.now):'Activate shield · €6,000','shield','',finished||p.shieldUntil>r.now,6000)}<small>Defense building halves disruption time. Sabotage never destroys your buildings or satellites.</small></section>
   </aside></div></main>`;
  if(c.view!=='base')this.world(c);this.live(c);if(focus){const el=Array.from(c.root.querySelectorAll('[data-match]')).find(b=>Object.entries(focus).every(([k,v])=>b.dataset[k]===v));if(el&&!el.disabled)el.focus({preventScroll:true});}
 },
 nodeInspector(c,p,n,finished){const r=c.room,owner=r.players.find(q=>q.id===n.owner),claimant=r.players.find(q=>q.id===n.claim?.by),owned=n.owner===p.id;
  return `<p class="eyebrow">NETWORK REGION</p><h2>${Utils.escape(Utils.country(n.countryId).properties.name)}</h2><p>${owner?`Operated by <strong style="color:${c.color(owner.id)}">${Utils.escape(owner.name)}</strong>`:'Unclaimed coverage. Connect this region to start earning recurring income.'}</p><div class="region-stat"><strong>${n.level?`Level ${n.level}`:'Open market'}</strong><span>${Utils.money(Math.max(1,n.level)*600)} / 5s</span></div>${n.claim?`<div class="signal-warning">${Utils.escape(claimant?.name||'Company')} is connecting. ${this.countdown(n.claim.end,r.now)}</div>`:''}
   ${owned?this.button('Upgrade coverage · '+Utils.money(n.level*6000),'upgrade-node','',finished||n.level>=3||Boolean(n.claim),n.level*6000)+this.button('Defend region · €4,000','defend-node','',finished||!n.claim,4000):this.button(owner?'Contest coverage · '+Utils.money(12000+n.level*4000):'Connect region · €6,000','connect','',finished||Boolean(n.claim)||Boolean(r.nodes.find(n=>n.claim?.by===p.id))||STRATEGY.owned(r,p.id).length>=p.satellites*2,owner?12000+n.level*4000:6000,'primary')}
   <p class="subtle">${owned?'Upgrade for more income and a stronger takeover requirement.':owner?`Takeovers require ${n.level+1} satellites and take 20s. The owner can defend before completion.`:'A new connection takes 10 seconds. Each satellite supports two regions.'}</p>
   <label>Choose a network region<select id="networkChoice">${r.nodes.map(x=>`<option value="${x.countryId}" ${x.countryId===n.countryId?'selected':''}>${Utils.escape(Utils.country(x.countryId).properties.name)}${x.owner?' · connected':''}</option>`).join('')}</select></label>${owner&&owner.id!==p.id?this.button('Inspect rival spaceport','rival',`data-target="${owner.id}"`):''}`;
 },
 baseInspector(c,p,q,rival,finished){const r=c.room;if(rival)return `<p class="eyebrow">RIVAL INTELLIGENCE</p><h2>${Utils.escape(q.name)}</h2><p>${Utils.escape(Utils.country(q.countryId).properties.name)} · ${q.satellites} satellites</p><p>${STRATEGY.owned(r,q.id).length} regions. Their buildings and launches are visible on the left.</p>${this.button('Disrupt network · €10,000','sabotage',`data-target="${q.id}"`,finished||!STRATEGY.level(p,'lab')||r.now-r.started<STRATEGY.grace||p.jamCooldown>r.now||q.shieldUntil>r.now||q.immuneUntil>r.now,10000,'danger')}<p>Disruption pauses network income for ${STRATEGY.level(q,'guard')?10:20} seconds. A shield can counter it immediately.</p><small>${!STRATEGY.level(p,'lab')?'Build a research lab first.':p.jamCooldown>r.now?'Sabotage cooldown: '+this.countdown(p.jamCooldown,r.now):q.shieldUntil>r.now?'Target shield: '+this.countdown(q.shieldUntil,r.now):q.immuneUntil>r.now?'Target protection: '+this.countdown(q.immuneUntil,r.now):'Sabotage available.'}</small>${this.button('Return to my base','view','data-view="base"')}`;
  const i=c.plot,type=p.plots[i],b=p.building,level=p.levels[i]||1;
  return `<p class="eyebrow">SPACEPORT / SITE ${i+1}</p><h2>${i>=p.plots.length?'Expand your grounds':type?STRATEGY.buildings[type]?.name||'Headquarters':'Ready to build'}</h2>${b?`<p>Building ${STRATEGY.buildings[b.type].name} · ${this.countdown(b.end,r.now)}</p>`:''}${i>=p.plots.length?this.button('Buy next land · '+Utils.money(4000+(p.plots.length-4)*2000),'expand','',finished,4000+(p.plots.length-4)*2000):!type?`<p>Place a facility on the highlighted land.</p><div class="facility-choices">${Object.entries(STRATEGY.buildings).map(([key,d])=>this.button(`<span>${d.name}<small>${Utils.money(d.cost)} · ${d.time/1000}s · ${d.power>0?d.power+' power':'+6 power'}</small></span>`,'build',`data-type="${key}"`,finished||Boolean(b),d.cost)).join('')}</div>`:type==='hq'?'<p>Your headquarters provides €300 every 5 seconds, even while your network is disrupted.</p>':`<p>Level ${level}. ${type==='solar'?'More levels increase available power.':type==='lab'?'Each level makes contracts 10% faster. Level 1 unlocks sabotage.':type==='pad'?'Upgrades make launch preparation faster.':type==='factory'?'Level 2 is required for an orbital station.':type==='guard'?'Incoming disruptions last only 10 seconds.':'Each level adds €2,000 income every 5 seconds.'}</p>${this.button('Upgrade · '+Utils.money(Math.round(STRATEGY.buildings[type].cost*level*.75)),'upgrade-building','',finished||Boolean(b)||level>=3,Math.round(STRATEGY.buildings[type].cost*level*.75))}`}
   <h3>Satellite assembly</h3><p>Factory + launch pad required. Choose a payload:</p><div class="blueprint-choices">${Object.entries(STRATEGY.blueprints).map(([key,d])=>this.button(`<span>${d.name} · ${Utils.money(d.cost)}<small>${d.description}</small></span>`,'launch',`data-type="${key}"`,finished||Boolean(p.production)||!STRATEGY.level(p,'factory')||!STRATEGY.level(p,'pad')||p.satellites>=24,d.cost)).join('')}</div>${p.production?`<p>Preparing ${STRATEGY.blueprints[p.production.type||'scout'].name}. Launch in ${this.countdown(p.production.end,r.now)}.</p>`:''}<p class="subtle">Orbital station: level 2 factory + level 2 lab + 6 satellites. Costs €90,000 and uses 4 power.</p>`;
 },
 live(c){const r=c.room,p=r.players.find(p=>p.id===c.self);if(!p)return;const funds=document.getElementById('strategyFunds'),income=document.getElementById('strategyIncome');if(funds)funds.textContent=Utils.money(p.money);if(income)income.textContent='+'+Utils.money(STRATEGY.income(r,p));c.root.querySelectorAll('[data-strategy-end]').forEach(el=>el.textContent=Math.max(0,Math.ceil((Number(el.dataset.strategyEnd)-r.now)/1000))+'s');c.root.querySelectorAll('[data-mission-end]').forEach(el=>el.value=Math.max(0,r.now-Number(el.dataset.missionStart)));const sel=document.getElementById('networkChoice');if(sel&&!sel.dataset.bound){sel.dataset.bound='true';sel.addEventListener('change',e=>c.click('select-node',{countryId:e.target.value}));}c.disable();},
 world(c){const r=c.room,svg=document.getElementById('strategyWorld');if(!svg)return;const projection=d3.geoNaturalEarth1().fitExtent([[24,36],[876,434]],{type:'Sphere'}),path=d3.geoPath(projection);
  svg.innerHTML=`<defs><radialGradient id="orbitGlow"><stop stop-color="#1b394c"/><stop offset="1" stop-color="#0b1825"/></radialGradient></defs><rect width="900" height="490" fill="url(#orbitGlow)"/><path d="${path({type:'Sphere'})}" fill="#132e42" stroke="#3b6177"/>${WORLD_DATA.features.map(f=>{const n=r.nodes.find(n=>n.countryId===f.id);return `<path d="${path(f)}" fill="${n?.owner?c.color(n.owner):n?'#496865':'#263f4c'}" stroke="${c.selectedNode===f.id?'#f1ffdf':'#577582'}" stroke-width="${c.selectedNode===f.id?2:.5}" ${n?`data-match="select-node" data-country-id="${f.id}" class="network-country"`:''}/>`;}).join('')}
   <g class="orbital-tracks">${r.players.map((p,i)=>`<ellipse cx="450" cy="235" rx="${360-i*17}" ry="${150-i*9}" transform="rotate(${i*23-35} 450 235)" fill="none" stroke="${c.color(p.id)}" opacity=".2" stroke-dasharray="3 7"/>`).join('')}</g>
   ${r.nodes.map(n=>{const f=Utils.country(n.countryId),point=baseSystem.landPoint(n.countryId),[x,y]=projection(point),owner=r.players.find(p=>p.id===n.owner),selected=c.selectedNode===n.countryId;return `<g role="button" tabindex="0" aria-label="${Utils.escape(f.properties.name)} network region" data-match="select-node" data-country-id="${n.countryId}" class="network-pin" transform="translate(${x} ${y})"><circle r="${selected?15:11}" fill="#0d1c25" stroke="${owner?c.color(owner.id):'#c9d9d3'}" stroke-width="2"/>${n.claim?'<circle r="18" fill="none" stroke="#f2bc70" stroke-dasharray="4 3" class="network-pulse"/>':''}<text text-anchor="middle" y="4" fill="${owner?c.color(owner.id):'#c9d9d3'}" font-size="11">${n.level||'+'}</text><title>${Utils.escape(f.properties.name+' · '+(owner?.name||'Unclaimed'))}</title></g>`;}).join('')}
   ${r.players.map((p,i)=>{const [x,y]=projection(p.coordinates);return `<g pointer-events="none"><circle cx="${x}" cy="${y}" r="4" fill="${c.color(p.id)}"/><text x="${x+(x>650?-12:12)}" y="${y-20-i%2*14}" text-anchor="${x>650?'end':'start'}" fill="${c.color(p.id)}" font-size="13" font-weight="600" stroke="#0a1420" stroke-width="4" paint-order="stroke">${Utils.escape(p.name)}</text></g>`;}).join('')}
   ${r.players.map((p,i)=>Array.from({length:Math.min(6,p.satellites)},(_,j)=>`<g class="orbit-satellite"><path d="M-8-3h5v6h-5m11-6h5v6H3M-2-2h4v4h-4" fill="${c.color(p.id)}"/><animateMotion dur="${28+i*7+j*4}s" begin="-${j*7}s" repeatCount="indefinite" path="M110 235 C110 65 790 65 790 235 C790 405 110 405 110 235"/></g>`).join('')).join('')}
   <text x="30" y="473" fill="#aac4d3" font-size="12" letter-spacing="1">SELECT A NETWORK MARKER · COLORED REGIONS EARN RECURRING INCOME</text>`;
 }
};
