const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c=vm.createContext({console});for(const f of ['vendor/d3.min.js','js/world-data.js','js/locale.js','js/config.js','js/base.js','js/match-rules.js','js/strategy-rules.js','js/spaceport-scene.js','js/strategy-view.js'])vm.runInContext(fs.readFileSync(__dirname+'/../'+f,'utf8'),c,{filename:f});const run=s=>vm.runInContext(s,c);let count=0;function test(name,fn){fn();count++;console.log('PASS '+name)}
function fresh(endless=true){run(`var r=MATCH_RULES.room(MATCH_RULES.player('a','Alpha','NLD'));r.players.push(MATCH_RULES.player('b','Beta','USA'));r.players.forEach(p=>p.ready=true);STRATEGY.upgrade(r,${endless});STRATEGY.start(r,0);var p=r.players[0],q=r.players[1];`)}
test('Solo has no time or revenue limit and reconnect income is consistent',()=>{fresh();run('p.revenue=900000;STRATEGY.advance(r,3600000)');assert.equal(run('r.status'),'running');assert.equal(run('p.money'),316000);const a=run('p.money');run('STRATEGY.advance(r,3600000)');assert.equal(run('p.money'),a)});
test('Regions pay only after connecting and cannot have two claimants',()=>{fresh();run('STRATEGY.action(r,"a","connect",{countryId:"NLD"},0)');assert.throws(()=>run('STRATEGY.action(r,"b","connect",{countryId:"NLD"},0)'));run('STRATEGY.advance(r,15000)');assert.equal(run('p.money'),95500);assert.equal(run('STRATEGY.owned(r,"a").length'),1);run('STRATEGY.advance(r,15000)');assert.equal(run('p.money'),95500)});
test('Income is identical for frequent ticks and delayed reconnect',()=>{fresh();run('STRATEGY.action(r,"a","connect",{countryId:"USA"},0);var saved=JSON.stringify(r);STRATEGY.advance(r,30555);var expected=p.money;var rem=p.incomeRemainder;r=JSON.parse(saved);p=r.players[0];for(var t=137;t<30555;t+=137)STRATEGY.advance(r,t);STRATEGY.advance(r,30555)');assert.equal(run('p.money'),run('expected'));assert.equal(run('p.incomeRemainder'),run('rem'))});
test('Build, upgrade, blueprint launch and passive bonuses follow actual completion',()=>{fresh();run('STRATEGY.action(r,"a","build",{type:"factory",plot:1},0);STRATEGY.advance(r,20000);STRATEGY.action(r,"a","build",{type:"pad",plot:2},20000);STRATEGY.advance(r,35000);STRATEGY.action(r,"a","launch",{type:"relay"},35000);STRATEGY.advance(r,59000)');assert.equal(run('p.fleet.relay'),1);assert.equal(run('p.satellites'),2);assert.equal(run('STRATEGY.income(r,p)'),500);run('STRATEGY.action(r,"a","upgrade-building",{plot:1},59000);STRATEGY.advance(r,71000)');assert.equal(run('p.levels[1]'),2);assert.throws(()=>run('STRATEGY.action(r,"a","build",{type:"station",plot:3},71000)'))});
test('Sabotage requires a lab, obeys truce and immunity, and is countered by shields',()=>{fresh();run('p.plots[1]="lab";p.levels[1]=1;r.nodes[0].owner="b";r.nodes[0].level=1');assert.throws(()=>run('STRATEGY.action(r,"a","sabotage",{target:"b"},89000)'));run('STRATEGY.action(r,"a","sabotage",{target:"b"},90000)');assert.equal(run('q.jamUntil'),110000);assert.equal(run('STRATEGY.income(r,q)'),300);assert.throws(()=>run('STRATEGY.action(r,"a","sabotage",{target:"b"},91000)'));run('STRATEGY.action(r,"b","shield",{},91000)');assert.equal(run('q.jamUntil'),91000);assert.equal(run('STRATEGY.income(r,q)'),900);assert.throws(()=>run('STRATEGY.action(r,"a","sabotage",{target:"a"},150000)'))});
test('Defenses halve disruption and defender can cancel a contested region',()=>{fresh();run('p.plots[1]="lab";p.levels[1]=1;q.plots[1]="guard";q.levels[1]=1;p.satellites=3;r.nodes[0].owner="b";r.nodes[0].level=1;STRATEGY.action(r,"a","sabotage",{target:"b"},90000);STRATEGY.action(r,"a","connect",{countryId:"USA"},90000)');assert.equal(run('q.jamUntil'),100000);assert.throws(()=>run('STRATEGY.action(r,"a","defend-node",{countryId:"USA"},90000)'));run('STRATEGY.action(r,"b","defend-node",{countryId:"USA"},95000);STRATEGY.advance(r,120000)');assert.equal(run('r.nodes[0].owner'),'b');assert.equal(run('r.nodes[0].claim'),null)});
test('Priority requests can only be claimed once per window and pay once',()=>{fresh();run('STRATEGY.action(r,"a","event",{},0);STRATEGY.advance(r,20000)');assert.equal(run('p.revenue'),24000);assert.throws(()=>run('STRATEGY.action(r,"a","event",{},20000)'));run('STRATEGY.advance(r,60000)');assert.equal(run('p.revenue'),24000);assert.throws(()=>run('STRATEGY.action(r,"a","event",{},60000)'))});
test('Online victory needs uninterrupted majority while solo keeps running',()=>{fresh(false);run('r.nodes.slice(0,7).forEach(n=>{n.owner="a";n.level=1});STRATEGY.advance(r,1);STRATEGY.advance(r,45000)');assert.equal(run('r.status'),'running');run('STRATEGY.advance(r,45001)');assert.equal(run('r.winner'),'a');fresh();run('r.nodes.slice(0,7).forEach(n=>{n.owner="a";n.level=1});STRATEGY.advance(r,1);STRATEGY.advance(r,80000)');assert.equal(run('r.status'),'running')});
test('Bots on all difficulties build, launch, connect and keep a solvent company',()=>{for(const difficulty of ['easy','normal','hard']){fresh();run(`var next=0;for(var t=1000;t<=600000;t+=1000){STRATEGY.advance(r,t);if(t>=next){STRATEGY.bot(r,'b',${JSON.stringify(difficulty)},t);next=t+({easy:12000,normal:5000,hard:1500}[${JSON.stringify(difficulty)}]);}}`);assert.ok(run('q.satellites>=6'),difficulty);assert.ok(run('STRATEGY.owned(r,"b").length>=3'),difficulty);assert.ok(run('q.money>=0'),difficulty);assert.ok(run('q.revenue>0'),difficulty)}});
test('Base artwork reflects buildings and keyboard-selectable sites',()=>{fresh();run('p.plots[1]="factory";p.levels[1]=1');const art=run('SPACEPORT_SCENE.render(p,0,1)');assert.match(art,/Site 2: Satellite factory/);assert.match(art,/role="button" tabindex="0"/);assert.match(art,/SATELLITE FACTORY/)});
console.log(count+' frontier checks passed.');
