-- Orbital Pact 4.0. Run this once in a dedicated Supabase project.
create extension if not exists pgcrypto;
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,username text unique not null check (char_length(username) between 3 and 20),rating integer not null default 1000,wins integer not null default 0,losses integer not null default 0,matches_played integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.lobbies (id uuid primary key default gen_random_uuid(),host_id uuid not null references auth.users(id) on delete cascade,host_name text not null check (char_length(host_name) between 3 and 20),name text not null check (char_length(name) between 3 and 48),status text not null default 'open' check (status in ('open','playing','closed')),max_players integer not null default 6 check (max_players between 2 and 12),player_count integer not null default 1 check (player_count between 0 and 12),settings jsonb not null default '{}'::jsonb,server_room text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.lobby_members (lobby_id uuid references public.lobbies(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,display_name text not null check (char_length(display_name) between 3 and 20),ready boolean not null default false,spectator boolean not null default false,joined_at timestamptz not null default now(),last_seen_at timestamptz not null default now(),primary key(lobby_id,user_id));
create table if not exists public.matches (id uuid primary key default gen_random_uuid(),lobby_id uuid references public.lobbies(id) on delete set null,status text not null default 'active' check (status in ('active','finished','abandoned')),server_key text unique not null,winner_id uuid references auth.users(id) on delete set null,settings jsonb not null default '{}'::jsonb,result jsonb,started_at timestamptz not null default now(),ended_at timestamptz);
create table if not exists public.match_players (match_id uuid references public.matches(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,display_name text not null,placement integer,score integer not null default 0,stats jsonb not null default '{}'::jsonb,primary key(match_id,user_id));

create or replace function public.refresh_lobby_count() returns trigger language plpgsql security definer set search_path=public as $$ begin update public.lobbies set player_count=(select count(*) from public.lobby_members where lobby_id=coalesce(new.lobby_id,old.lobby_id)),updated_at=now() where id=coalesce(new.lobby_id,old.lobby_id);return coalesce(new,old);end $$;
drop trigger if exists lobby_count_after_change on public.lobby_members;
create trigger lobby_count_after_change after insert or delete on public.lobby_members for each row execute function public.refresh_lobby_count();

alter table public.profiles enable row level security;alter table public.lobbies enable row level security;alter table public.lobby_members enable row level security;alter table public.matches enable row level security;alter table public.match_players enable row level security;
create policy "profiles readable" on public.profiles for select using (true);create policy "profile owner inserts" on public.profiles for insert to authenticated with check (auth.uid()=id);create policy "profile owner updates" on public.profiles for update to authenticated using (auth.uid()=id);
create policy "open lobbies readable" on public.lobbies for select using (status='open' or host_id=auth.uid());create policy "host creates lobby" on public.lobbies for insert to authenticated with check (host_id=auth.uid());create policy "host updates lobby" on public.lobbies for update to authenticated using (host_id=auth.uid());create policy "host deletes lobby" on public.lobbies for delete to authenticated using (host_id=auth.uid());
create policy "members readable" on public.lobby_members for select using (true);create policy "member joins self" on public.lobby_members for insert to authenticated with check (user_id=auth.uid());create policy "member updates self" on public.lobby_members for update to authenticated using (user_id=auth.uid());create policy "member leaves self" on public.lobby_members for delete to authenticated using (user_id=auth.uid());
create policy "finished matches readable" on public.matches for select using (status='finished');create policy "match players readable" on public.match_players for select using (true);

do $$ begin alter publication supabase_realtime add table public.lobbies;exception when duplicate_object then null;end $$;
do $$ begin alter publication supabase_realtime add table public.lobby_members;exception when duplicate_object then null;end $$;
