const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json','access-control-allow-origin':'*'}});
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));

export class MatchRoom{
  constructor(state,env){this.storage=state.storage;this.env=env;this.sessions=new Map();this.game=null;this.ready=this.load();}
  async load(){this.game=await this.storage.get('game')||{version:1,status:'waiting',tick:0,createdAt:Date.now(),settings:{objective:'influence',alliances:true,sabotage:true},players:{},control:{},events:[]};}
  async fetch(request){await this.ready;const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'}});if(request.headers.get('Upgrade')==='websocket')return this.upgrade(url);if(request.method==='GET')return json(this.publicState());if(request.method==='POST'){let body;try{body=await request.json();}catch{return json({error:'Invalid JSON'},400);}if(body.type==='configure'&&this.game.status==='waiting'){this.game.settings={...this.game.settings,...this.cleanSettings(body.settings)};await this.persist();return json(this.publicState());}return json({error:'Unsupported command'},400);}return json({error:'Method not allowed'},405);}
  upgrade(url){const pair=new WebSocketPair(),client=pair[0],server=pair[1];server.accept();const id=crypto.randomUUID(),name=this.cleanName(url.searchParams.get('name'));this.sessions.set(id,server);this.game.players[id]={id,name,credits:Number(this.game.settings.startMoney)||100000,score:0,influence:4,relays:0,satellites:1,defense:0,ready:false,connected:true,lastAction:0};this.bind(id,server);server.send(JSON.stringify({type:'welcome',playerId:id,state:this.publicState()}));this.event(`${name} entered the sector.`);this.persist();this.broadcastState();return new Response(null,{status:101,webSocket:client});}
  bind(id,ws){ws.addEventListener('message',event=>this.onMessage(id,event.data));ws.addEventListener('close',()=>{const p=this.game.players[id];if(p)p.connected=false;this.sessions.delete(id);this.event(`${p?.name||'A commander'} disconnected.`);this.persist();this.broadcastState();});ws.addEventListener('error',()=>ws.close());}
  async onMessage(id,raw){let msg;try{msg=JSON.parse(raw);}catch{return this.error(id,'Invalid message.');}const p=this.game.players[id];if(!p)return;if(msg.type==='ping')return this.send(id,{type:'pong',t:Date.now()});if(msg.type==='hello'){p.name=this.cleanName(msg.name);return this.broadcastState();}if(msg.type==='ready'){p.ready=Boolean(msg.ready);if(Object.values(this.game.players).filter(x=>x.connected).length>=2&&Object.values(this.game.players).filter(x=>x.connected).every(x=>x.ready))this.game.status='active';await this.persist();return this.broadcastState();}if(msg.type!=='action'||this.game.status==='ended')return this.error(id,'Command rejected.');const now=Date.now();if(now-p.lastAction<250)return this.error(id,'Action rate limited.');p.lastAction=now;const result=this.applyAction(p,msg);if(result.error)return this.error(id,result.error);this.game.tick++;this.checkWinner();await this.persist();this.broadcast({type:'event',message:result.message});this.broadcastState();}
  applyAction(p,msg){const action=msg.action;if(action==='relay'){const country=String(msg.countryId||'').slice(0,3).toUpperCase(),cost=125000;if(!/^[A-Z]{3}$/.test(country))return {error:'Invalid country.'};if(p.credits<cost)return {error:'Not enough credits.'};if(this.game.control[country]===p.id)return {error:'You already control this relay.'};p.credits-=cost;p.relays++;p.influence=clamp(p.influence+3,0,100);p.score+=35;this.game.control[country]=p.id;return {message:`${p.name} deployed a relay in ${country}.`};}if(action==='donate'){if(!this.game.settings.alliances)return {error:'Alliances are disabled.'};const target=this.game.players[msg.target],amount=clamp(Math.floor(Number(msg.amount)||0),1000,100000);if(!target||target.id===p.id)return {error:'Invalid ally.'};if(p.credits<amount)return {error:'Not enough credits.'};p.credits-=amount;target.credits+=amount;p.score+=Math.floor(amount/5000);return {message:`${p.name} supported ${target.name}.`};}if(action==='sabotage'){if(!this.game.settings.sabotage)return {error:'Operations are disabled.'};const target=this.game.players[msg.target];if(!target||target.id===p.id)return {error:'Invalid target.'};const types={cyber:{cost:18000,power:12000},jam:{cost:30000,power:24000},intercept:{cost:48000,power:42000}},op=types[msg.operation]||types.cyber;if(p.credits<op.cost)return {error:'Not enough credits.'};p.credits-=op.cost;const blocked=Math.random()<target.defense/140;if(!blocked){const value=Math.min(target.credits,op.power);target.credits-=value;p.credits+=Math.floor(value*.6);p.score+=20;}return {message:blocked?`${target.name} blocked an orbital operation.`:`${p.name} disrupted ${target.name}.`};}if(action==='defend'){if(p.credits<30000)return {error:'Not enough credits.'};p.credits-=30000;p.defense=clamp(p.defense+25,0,100);p.score+=12;return {message:`${p.name} strengthened orbital defenses.`};}if(action==='contract')return {error:'Client-selected rewards are not accepted. Server mission completion is required.'};return {error:'Unknown action.'};}
  checkWinner(){const objective=this.game.settings.objective||'influence',target={influence:60,economy:2000000,network:18,score:1000}[objective]||60;for(const p of Object.values(this.game.players)){const value=objective==='influence'?p.influence:objective==='economy'?p.credits:objective==='network'?p.relays:p.score;if(value>=target){this.game.status='ended';this.game.winner=p.id;this.event(`${p.name} won through ${objective}.`);break;}}}
  cleanSettings(s={}){return {difficulty:['easy','normal','hard','expert'].includes(s.difficulty)?s.difficulty:'normal',pace:['slow','standard','fast'].includes(s.pace)?s.pace:'standard',objective:['influence','economy','network','score'].includes(s.objective)?s.objective:'influence',startMoney:clamp(Number(s.startMoney)||100000,50000,150000),fog:s.fog!==false,alliances:s.alliances!==false,sabotage:s.sabotage!==false,maxPlayers:clamp(Number(s.maxPlayers)||6,2,12)};}
  cleanName(value){const name=String(value||'').replace(/[^a-zA-Z0-9 _-]/g,'').trim().slice(0,20);return name||`Anon${String(Math.floor(Math.random()*10000)).padStart(4,'0')}`;}
  publicState(){return {...this.game,events:this.game.events.slice(-20),players:Object.fromEntries(Object.entries(this.game.players).map(([id,p])=>[id,{...p,lastAction:undefined}]))};}
  event(message){this.game.events.push({message,time:Date.now()});this.game.events=this.game.events.slice(-50);this.broadcast({type:'event',message});}
  error(id,message){this.send(id,{type:'error',message});}
  send(id,message){try{this.sessions.get(id)?.send(JSON.stringify(message));}catch{}}
  broadcast(message){const body=JSON.stringify(message);for(const ws of this.sessions.values())try{ws.send(body);}catch{}}
  broadcastState(){this.broadcast({type:'state',state:this.publicState(),players:Object.values(this.game.players).filter(p=>p.connected).length});}
  async persist(){await this.storage.put('game',this.game);}
}

export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname==='/health')return json({ok:true,service:'orbital-pact-match'});const match=url.pathname.match(/^\/match\/([a-zA-Z0-9_-]{3,80})$/);if(!match)return json({error:'Not found'},404);return env.MATCH_ROOM.get(env.MATCH_ROOM.idFromName(match[1])).fetch(request);}};
