'use strict';
const diplomacySystem={
  rivals:[
    {id:'helios',name:'Helios Array',specialty:'Observation',power:72},
    {id:'kepler',name:'Kepler Relay',specialty:'Communications',power:61},
    {id:'zenith',name:'Zenith Systems',specialty:'Navigation',power:83},
    {id:'aurora',name:'Aurora Dynamics',specialty:'Research',power:55}
  ],
  ensure(state){if(!state.diplomacy)state.diplomacy={relations:{},cooldowns:{},requests:[]};state.diplomacy.requests=Array.isArray(state.diplomacy.requests)?state.diplomacy.requests:[];for(const r of this.rivals)if(!state.diplomacy.relations[r.id])state.diplomacy.relations[r.id]={status:'neutral',trust:50,donated:0,intelShared:false,jointProject:null};return state.diplomacy;},
  ally(state,id){this.ensure(state);const rel=state.diplomacy.relations[id];if(!rel)return {error:'Unknown corporation.'};if(rel.status==='allied')return {error:'You are already allied.'};if(rel.trust<35)return {error:'Trust is too low for an alliance.'};rel.status='allied';rel.trust=Math.min(100,rel.trust+10);return {success:true};},
  breakAlliance(state,id){this.ensure(state);const rel=state.diplomacy.relations[id];if(!rel||rel.status!=='allied')return {error:'No active alliance.'};rel.status='neutral';rel.trust=Math.max(0,rel.trust-25);return {success:true};},
  donate(state,id,amount){this.ensure(state);const rel=state.diplomacy.relations[id],n=Math.max(0,Math.floor(Number(amount)||0));if(!rel||rel.status!=='allied')return {error:'You can only donate to allies.'};if(n<1000)return {error:'Minimum donation is €1,000.'};if(state.money<n)return {error:'Not enough funds.'};state.money-=n;state.totalCosts+=n;if(state.strategy?.rivals?.[id])state.strategy.rivals[id].money+=n;rel.donated+=n;rel.trust=Math.min(100,rel.trust+Math.max(1,Math.floor(n/25000)));return {success:true,amount:n};},
  sabotage(state,id,type='cyber'){this.ensure(state);const rel=state.diplomacy.relations[id],now=state.playTime||0,cool=state.diplomacy.cooldowns[id]||0;if(!rel)return {error:'Unknown target.'};if(rel.status==='allied')return {error:'Break the alliance before targeting this corporation.'};if(now<cool)return {error:'Operations team is still on cooldown.'};const types={cyber:{cost:18000,chance:.68,reward:[12000,28000],cooldown:90000,label:'Cyber breach'},jam:{cost:30000,chance:.58,reward:[28000,52000],cooldown:120000,label:'Signal jam'},intercept:{cost:48000,chance:.48,reward:[50000,90000],cooldown:150000,label:'Contract intercept'}},op=types[type]||types.cyber;if(state.money<op.cost)return {error:`You need ${Utils.money(op.cost)} for this operation.`};state.money-=op.cost;state.totalCosts+=op.cost;state.diplomacy.cooldowns[id]=now+op.cooldown;rel.trust=Math.max(0,rel.trust-20);const defense=Number(state.strategy?.rivals?.[id]?.defense)||0,success=Math.random()<Math.max(.2,op.chance-defense/400);if(success){const reward=op.reward[0]+Math.floor(Math.random()*(op.reward[1]-op.reward[0]));const target=state.strategy?.rivals?.[id];const recovered=target?Math.min(reward,target.money):reward;if(target)target.money-=recovered;state.money+=recovered;if(state.strategy)state.strategy.score+=25;return {success:true,reward:recovered,message:`${op.label} succeeded. Recovered ${Utils.money(recovered)} in strategic value.`};}return {success:true,reward:0,message:`${op.label} failed. The rival blocked the operation.`};}
};
