'use strict';
class Game {
  constructor(){this.state=saveSystem.fresh();this.ui=null;this.map=null;this.lastFrame=0;this.lastUI=0;this.lastSave=0;this.bankrupt=false;this.refreshAt=0;}
  init(){
    const saved=saveSystem.load();this.state=saved||saveSystem.fresh();
    diplomacySystem.ensure(this.state);strategySystem.ensure(this.state);
    if(!saved){this.state.satellites.push(satelliteSystem.create(this.state,'Scout-1'));const starts=['NLD','USA','BRA','JPN','AUS'];this.state.offers=starts.map((id,i)=>contractSystem.create(this.state,id,i));this.log('Welkom bij Space Corp. Je Scout-1 is klaar voor de eerste opdracht.');}
    this.ui=new UISystem(this);this.ui.init();this.map=new WorldMap(this,id=>this.ui.selectCountry(id,false));this.ui.render();
    if(saveSystem.message){this.log(saveSystem.message,'warning');this.ui.toast(saveSystem.message);}
    this.save();
    document.addEventListener('visibilitychange',()=>{this.lastFrame=performance.now();if(document.hidden)this.save();});
    window.addEventListener('pagehide',()=>this.save());window.addEventListener('beforeunload',()=>this.save());
    const frame=now=>{const dt=this.lastFrame?Math.min(1000,Math.max(0,now-this.lastFrame)):0;this.lastFrame=now;if(!document.hidden){if(!this.state.paused)this.update(dt*this.state.speed);if(now-this.lastUI>=250){this.ui.updateLive();this.lastUI=now;}if(this.ui.page==='operations'&&now-(this.lastMap||0)>33){this.map.draw();this.lastMap=now;}if(now-this.lastSave>CONFIG.saveInterval){this.save();this.lastSave=now;}}this.frame=requestAnimationFrame(frame);};this.frame=requestAnimationFrame(frame);
  }
  update(dt){
    if(!Number.isFinite(dt)||dt<=0||this.state.paused)return;
    const state=this.state;dt*=({slow:.75,standard:1,fast:1.5}[state.matchSettings?.pace]||1);state.playTime+=dt;const maintenance=satelliteSystem.update(state,dt);const paid=Math.min(state.money,maintenance);state.money-=paid;state.totalCosts+=paid;
    const completed=contractSystem.update(state,dt);let dirty=false;
    for(const m of completed){this.log(`${CONFIG.contractTypes[m.typeIndex].name} completed. ${Utils.money(m.reward)} received; ${Utils.money(m.reward-m.cost)} profit.`,'success');this.ui?.toast(`Contract complete: +${Utils.money(m.reward)}`);strategySystem.ensure(state).score+=30;if(strategySystem.has(state,'lunar-telemetry'))state.research+=5;dirty=true;}
    const level=Utils.level(state.totalMoneyEarned);if(level!==state.level){state.level=level;this.log(`Bedrijfslevel ${level} bereikt: ${CONFIG.levelNames[level-1]}.`,'success');this.ui?.toast(`Level ${level}: ${CONFIG.levelNames[level-1]}`);dirty=true;}
    if(state.money<=0&&!this.bankrupt){this.bankrupt=true;this.log('Je saldo is leeg. Lopende contracten worden afgemaakt. Onderhoud bouwt geen schuld op.','warning');this.ui?.toast('Geen geld meer. Rond je lopende contracten af.');dirty=true;}else if(state.money>1)this.bankrupt=false;
    const worldEvent=eventSystem.update(state);if(worldEvent){this.log(`${worldEvent.title}: ${worldEvent.text}`,worldEvent.value>=0?'success':'warning');this.ui?.toast(worldEvent.title);dirty=true;}
    const strategyUpdate=strategySystem.update(state);if(strategyUpdate?.winner){this.log(`${strategyUpdate.winner==='player'?'Victory':'Defeat'}: ${strategyUpdate.objective.name}.`,strategyUpdate.winner==='player'?'success':'warning');this.state.paused=true;this.ui?.showEnd?.(strategyUpdate);dirty=true;}else if(strategyUpdate?.changed){this.map&&(this.map.dirty=true);dirty=true;}
    if(dirty)this.changed();
  }
  log(message,type='info'){this.state.log.push({message,type,time:this.state.playTime});this.state.log=this.state.log.slice(-100);}
  changed(){this.ui?.render();this.save();}
  save(){const success=saveSystem.save(this.state);if(this.ui){document.getElementById('saveStatus').textContent=success?'Opgeslagen op dit apparaat':'Opslaan niet mogelijk in deze browser';}return success;}
  accept(id,satelliteId){const result=contractSystem.accept(this.state,id,satelliteId);if(result.error){this.ui?.toast(result.error,true);return false;}const m=result.mission;this.log(`Contract gestart: ${CONFIG.contractTypes[m.typeIndex].name}. Startkosten: ${Utils.money(m.cost)}.`);this.changed();this.ui?.toast('Contract gestart. Je satelliet is aan het werk.');return true;}
  buySatellite(type){const def=CONFIG.satelliteTypes[type];if(!def||this.state.money<def.price){this.ui?.toast('Onvoldoende geld voor deze satelliet.',true);return false;}this.state.money-=def.price;this.state.totalCosts+=def.price;const sat=satelliteSystem.create(this.state,type);this.state.satellites.push(sat);this.log(`${sat.name} gelanceerd voor ${Utils.money(def.price)}.`,'success');this.changed();this.ui?.toast(`${sat.name} is toegevoegd aan je vloot.`);return true;}
  buyUpgrade(key){const result=upgradeSystem.buy(this.state,key);if(result.error){this.ui?.toast(result.error,true);return false;}this.state.totalCosts+=result.info.cost;this.log(`${result.info.name} verbeterd naar niveau ${this.state.upgrades[key]}.`,'success');this.changed();this.ui?.toast('Verbetering toegepast op je vloot.');return true;}
  repair(id){const sat=this.state.satellites.find(s=>s.id===id);if(!sat)return false;if(sat.activeContract!==null){this.ui?.toast('Wacht tot het contract is afgerond.',true);return false;}const cost=satelliteSystem.repairCost(sat);if(this.state.money<cost){this.ui?.toast('Onvoldoende geld voor reparatie.',true);return false;}this.state.money-=cost;this.state.totalCosts+=cost;sat.health=100;this.log(`${sat.name} gerepareerd voor ${Utils.money(cost)}.`,'success');this.changed();return true;}
  refresh(countryId=null){const now=Date.now();if(now<this.refreshAt){this.ui?.toast('Wacht even voordat je opnieuw contracten zoekt.',true);return false;}contractSystem.generate(this.state,countryId);this.refreshAt=now+3000;this.log(countryId?`Nieuw aanbod in ${Utils.country(countryId)?.properties.name||'dit land'}.`:'Nieuw wereldwijd contractaanbod ontvangen.');this.changed();return true;}
  togglePause(){this.state.paused=!this.state.paused;this.lastFrame=performance.now();this.ui?.updateLive();this.save();}
  toggleSpeed(){this.state.speed=this.state.speed===1?3:1;this.ui?.updateLive();this.save();}

  setMode(mode,difficulty='normal',settings={}){this.state.mode=mode;this.state.difficulty=difficulty;this.state.matchSettings={...this.state.matchSettings,...settings};const defaultStart={easy:150000,normal:100000,hard:75000,expert:50000}[difficulty]||100000,startMoney=Number(settings.startMoney)||defaultStart;if(this.state.playTime<1000&&this.state.completedContracts===0)this.state.money=startMoney;this.log(`${mode==='multiplayer'?'Multiplayer sector':'Solo campaign'} configured: ${difficulty}.`);this.changed();}
  alliance(id){if(this.state.matchSettings?.alliances===false){this.ui?.toast('Alliances are disabled for this match.',true);return false;}const r=diplomacySystem.ally(this.state,id);if(r.error){this.ui?.toast(r.error,true);return false;}this.log(`Alliance formed with ${diplomacySystem.rivals.find(x=>x.id===id)?.name}.`,'success');this.changed();return true;}
  breakAlliance(id){const r=diplomacySystem.breakAlliance(this.state,id);if(r.error){this.ui?.toast(r.error,true);return false;}this.log('Alliance ended.','warning');this.changed();return true;}
  donate(id,amount=10000){if(this.state.matchSettings?.alliances===false){this.ui?.toast('Alliances are disabled for this match.',true);return false;}const r=diplomacySystem.donate(this.state,id,amount);if(r.error){this.ui?.toast(r.error,true);return false;}this.log(`Donated ${Utils.money(r.amount)} to an ally.`,'success');this.changed();return true;}
  sabotage(id,type='cyber'){if(this.state.matchSettings?.sabotage===false){this.ui?.toast('Sabotage is disabled for this match.',true);return false;}const r=diplomacySystem.sabotage(this.state,id,type);if(r.error){this.ui?.toast(r.error,true);return false;}this.log(r.message,r.reward?'success':'warning');this.ui?.toast(r.message,!r.reward);if(typeof onlineSystem!=='undefined')onlineSystem.send('action',{action:'sabotage',target:id,operation:type});this.changed();return true;}
  buildRelay(countryId){const country=Utils.country(countryId);if(!country){this.ui?.toast('Select a country first.',true);return false;}const cost=strategySystem.relayCost(this.state);if(this.state.money<cost){this.ui?.toast(`You need ${Utils.money(cost)} to deploy a ground relay.`,true);return false;}if(this.state.orbitalProjects.some(p=>p.countryId===countryId&&p.owner!=='rival')){this.ui?.toast('You already control a relay here.',true);return false;}this.state.money-=cost;this.state.totalCosts+=cost;this.state.orbitalProjects=this.state.orbitalProjects.filter(p=>p.countryId!==countryId);this.state.orbitalProjects.push({id:`relay-${Date.now()}`,countryId,type:'relay',owner:'player',builtAt:this.state.playTime});const strategy=strategySystem.ensure(this.state);strategy.control[countryId]='player';strategy.score+=35;this.log(`Ground relay deployed in ${country.properties.name}.`,'success');if(typeof onlineSystem!=='undefined')onlineSystem.send('action',{action:'relay',countryId});this.changed();this.map&&(this.map.dirty=true);this.map?.draw();return true;}
  researchNode(id){const r=strategySystem.research(this.state,id);if(r.error){this.ui?.toast(r.error,true);return false;}this.log(`${r.node.name} research completed.`,'success');this.ui?.toast(`${r.node.name} unlocked.`);this.changed();return true;}
  defend(){const r=strategySystem.defend(this.state);if(r.error){this.ui?.toast(r.error,true);return false;}this.log(`Orbital defense raised to ${r.value}%.`,'success');this.changed();return true;}
  jointProject(id){const r=strategySystem.jointProject(this.state,id);if(r.error){this.ui?.toast(r.error,true);return false;}this.log(`Joint orbital project started with ${diplomacySystem.rivals.find(x=>x.id===id)?.name}.`,'success');this.changed();return true;}
  setObjective(id){if(!strategySystem.chooseObjective(this.state,id))return false;this.state.matchSettings.objective=id;this.log(`Victory condition changed to ${strategySystem.objectiveTypes[id].name}.`);this.changed();return true;}
  newGame(options={}){this.state=saveSystem.fresh();const mode=options.mode||'solo',difficulty=options.difficulty||'normal',settings={...(options.settings||{})};this.state.mode=mode;this.state.difficulty=difficulty;this.state.matchSettings={...this.state.matchSettings,...settings};const defaultStart={easy:150000,normal:100000,hard:75000,expert:50000}[difficulty]||100000;this.state.money=Number(settings.startMoney)||defaultStart;this.state.satellites.push(satelliteSystem.create(this.state,'Scout-1'));contractSystem.generate(this.state);diplomacySystem.ensure(this.state);strategySystem.ensure(this.state);strategySystem.chooseObjective(this.state,settings.objective||'influence');this.state.strategy.endless=Boolean(settings.endless);this.bankrupt=false;this.refreshAt=0;this.log(`${mode==='multiplayer'?'Multiplayer sector':'New solo campaign'} started on ${difficulty} difficulty.`);if(this.ui)this.ui.countryId=null;this.map?.reset();this.changed();this.ui?.navigate('operations');}
}
const game=new Game();
window.addEventListener('DOMContentLoaded',()=>game.init());
