'use strict';
const onlineSystem={
  sessionKey:'orbitalPact_online_v1',socket:null,listeners:new Set(),
  config(){return window.ORBITAL_CONFIG||{};},
  enabled(){return false; /* Live rollout remains disabled until the shared authoritative simulation and authentication are integrated. */},
  workerEnabled(){return Boolean(this.config().matchServerUrl);},
  headers(token=null){const c=this.config();return {'apikey':c.supabaseAnonKey,'Authorization':`Bearer ${token||c.supabaseAnonKey}`,'Content-Type':'application/json'};},
  session(){try{return JSON.parse(localStorage.getItem(this.sessionKey)||'null');}catch{return null;}},
  async anonymousSession(){if(!this.enabled())return null;const old=this.session();if(old?.access_token&&old?.expires_at>Date.now()/1000+30)return old;const r=await fetch(`${this.config().supabaseUrl}/auth/v1/signup`,{method:'POST',headers:this.headers(),body:'{}'});if(!r.ok)throw new Error('Anonymous login is disabled in Supabase.');const data=await r.json(),session=data.access_token?data:data.session;if(!session)throw new Error('No Supabase session returned.');session.expires_at=Date.now()/1000+(session.expires_in||3600);localStorage.setItem(this.sessionKey,JSON.stringify(session));return session;},
  async lobbies(){if(!this.enabled())return [];const r=await fetch(`${this.config().supabaseUrl}/rest/v1/lobbies?status=eq.open&select=*&order=created_at.desc&limit=30`,{headers:this.headers()});if(!r.ok)throw new Error('Could not load live lobbies.');return (await r.json()).map(x=>({id:x.id,name:x.name,host:x.host_name||'Commander',players:x.player_count||1,maxPlayers:x.max_players,difficulty:x.settings?.difficulty||'normal',pace:x.settings?.pace||'standard',startMoney:x.settings?.startMoney||100000,fog:x.settings?.fog!==false,alliances:x.settings?.alliances!==false,sabotage:x.settings?.sabotage!==false,online:true,status:x.status}));},
  async createLobby(profile,settings){const session=await this.anonymousSession();const payload={host_id:session.user?.id,name:`${profile.name}'s Sector`,host_name:profile.name,max_players:Number(settings.maxPlayers)||6,settings,status:'open'};const r=await fetch(`${this.config().supabaseUrl}/rest/v1/lobbies`,{method:'POST',headers:{...this.headers(session.access_token),'Prefer':'return=representation'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Could not create the online lobby.');return (await r.json())[0];},
  async joinLobby(lobby,profile){const session=await this.anonymousSession();const r=await fetch(`${this.config().supabaseUrl}/rest/v1/lobby_members`,{method:'POST',headers:{...this.headers(session.access_token),'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({lobby_id:lobby.id,user_id:session.user.id,display_name:profile.name})});if(!r.ok)throw new Error('Could not join this lobby.');return {...lobby,players:Math.min(lobby.maxPlayers,(lobby.players||1)+1),online:true};},
  connect(matchId,profile){if(!this.enabled()||!this.workerEnabled())return false;this.disconnect();const base=this.config().matchServerUrl.replace(/^http/,'ws').replace(/\/$/,'');const socket=new WebSocket(`${base}/match/${encodeURIComponent(matchId)}?name=${encodeURIComponent(profile.name)}`);this.socket=socket;socket.onmessage=e=>{try{const msg=JSON.parse(e.data);for(const fn of this.listeners)fn(msg);}catch{}};socket.onopen=()=>socket.send(JSON.stringify({type:'hello',name:profile.name}));return true;},
  send(type,payload={}){if(this.socket?.readyState===WebSocket.OPEN){this.socket.send(JSON.stringify({type,...payload}));return true;}return false;},
  on(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn);},
  disconnect(){try{this.socket?.close();}catch{}this.socket=null;}
};
