'use strict';
const ICON_PATHS={
  globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
  satellite:'<path d="m9 7 8 8-4 4-8-8zM5 3l4 4-4 4-4-4zm14 10 4 4-4 4-4-4zM13 11l4-4m-3-3a7 7 0 0 1 7 7m-7-3a3 3 0 0 1 3 3"/>',
  briefcase:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V4h8v3M3 12l9 3 9-3M12 12v5"/>',
  layers:'<path d="m12 3 10 5-10 5L2 8zm-9 9 9 5 9-5M3 17l9 5 9-5"/>',
  chart:'<path d="M4 3v18h18M9 17v-5m5 5V7m5 10V4"/>',
  activity:'<path d="M2 12h4l3-8 5 16 3-8h5"/>',
  radar:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="m12 12 7-7"/><circle cx="12" cy="12" r="1"/>',
  focus:'<path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/><circle cx="12" cy="12" r="3"/>',
  trend:'<path d="m3 17 6-6 4 4 8-11M15 4h6v6"/>',
  shield:'<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6zM8 12l3 3 5-6"/>',
  help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 5m0 3h.01"/>',
  pause:'<path d="M8 5v14M16 5v14"/>',
  play:'<path d="m8 4 12 8-12 8z"/>',
  refresh:'<path d="M20 10a8 8 0 0 0-14-5L3 8m0-5v5h5M4 14a8 8 0 0 0 14 5l3-3m0 5v-5h-5"/>',
  cloud:'<path d="M6 18a4 4 0 0 1-1-8 7 7 0 0 1 13-1 4.5 4.5 0 0 1 0 9z"/>',
  bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-7z"/>',
  check:'<path d="m4 12 5 5L20 6"/>',
  arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>'
};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICON_PATHS[name]||ICON_PATHS.globe}</svg>`;
class UISystem{
  constructor(game){this.game=game;this.page='operations';this.countryId=null;this.dialog=document.getElementById('detailDialog');this.openOffer=null;}
  get state(){return this.game.state;}
  init(){
    document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
    document.querySelectorAll('.nav-button').forEach(el=>{const label=el.textContent.trim().replace(/\d+$/,'').trim();el.title=label;el.setAttribute('aria-label',label);if(el.dataset.page===this.page)el.setAttribute('aria-current','page');});
    const select=document.getElementById('countrySelect');
    WORLD_DATA.features.filter(f=>f.properties.region!=='Antarctica').sort((a,b)=>a.properties.name.localeCompare(b.properties.name,'nl')).forEach(f=>{const o=document.createElement('option');o.value=f.id;o.textContent=f.properties.name;select.appendChild(o);});
    select.addEventListener('change',()=>this.selectCountry(select.value||null));
    document.addEventListener('click',e=>{
      const nav=e.target.closest('[data-page]');if(nav){this.navigate(nav.dataset.page);return;}
      const button=e.target.closest('[data-action]');if(!button||button.disabled)return;const id=Number(button.dataset.id);
      switch(button.dataset.action){case'offer':this.showContract(id);break;case'buy':this.game.buySatellite(button.dataset.type);break;case'upgrade':this.game.buyUpgrade(button.dataset.key);break;case'repair':this.game.repair(id);break;case'satellite':this.showSatellite(id);break;case'country':this.navigate('operations');this.selectCountry(button.dataset.country);break;}
    });
    const bind=(id,fn)=>document.getElementById(id).addEventListener('click',fn);
    bind('refreshContracts',()=>this.game.refresh());bind('refreshMapOffers',()=>this.game.refresh(this.countryId));
    bind('pauseButton',()=>this.game.togglePause());bind('speedButton',()=>this.game.toggleSpeed());
    bind('globeButton',()=>this.game.map.setMode('globe'));bind('flatButton',()=>this.game.map.setMode('flat'));
    bind('zoomIn',()=>this.game.map.changeZoom(1.2));bind('zoomOut',()=>this.game.map.changeZoom(1/1.2));bind('resetMap',()=>this.game.map.reset());
    bind('closeDialog',()=>this.dialog.close());this.dialog.addEventListener('click',e=>{if(e.target===this.dialog){const r=this.dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.dialog.close();}});
    this.dialog.addEventListener('close',()=>{this.openOffer=null;});bind('helpButton',()=>this.showHelp());bind('newGameButton',()=>this.confirmNewGame());
    bind('saveButton',()=>{const success=this.game.save();this.toast(success?'Progress saved.':'This browser could not save progress.',!success);});
    bind('clearLogButton',()=>{this.state.log=[];this.game.log('Activity cleared.');this.game.changed();});
    bind('rematchButton',()=>{document.getElementById('endDialog').close();this.game.newGame({mode:this.state.mode,difficulty:this.state.difficulty,settings:{...this.state.matchSettings}});});
    bind('endContinueButton',()=>{strategySystem.keepExploring(this.state);document.getElementById('endDialog').close();this.game.changed();});
    document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();this.navigate('operations');});
    this.initOrbitalPact();
  }
  navigate(page){
    const copy={operations:['Mission Control','ORBITAL OPERATIONS','The world is within reach.','Build your network and outmaneuver every rival.'],strategy:['Strategy','MATCH COMMAND','Control the orbital economy.','Track rivals, choose your victory route and secure the planet.'],contracts:['Contracts','CONTRACT NETWORK','Your next mission.','Deliver data, earn credits and build your reputation.'],fleet:['Fleet','SATELLITE CONTROL','Expand your reach.','Manage your satellites and launch new hardware.'],upgrades:['Research','TECHNOLOGY','Choose your advantage.','Develop new abilities and improve your whole fleet.'],diplomacy:['Diplomacy','ORBITAL DIPLOMACY','Trust is a resource.','Form alliances, support partners or disrupt your rivals.'],multiplayer:['Multiplayer','PUBLIC NETWORK','Choose your sector.','Browse public lobbies or launch a custom match.'],company:['Company','COMPANY OVERVIEW','From first launch to orbital power.','Review results, match history and milestones.'],log:['Activity','OPERATION HISTORY','Every move in one place.','Review launches, contracts and strategic events.']};
    if(!copy[page])return;this.page=page;const [label,eyebrow,title,description]=copy[page];
    for(const [id,text]of Object.entries({pageLabel:label,pageEyebrow:eyebrow,pageTitle:title,pageDescription:description}))document.getElementById(id).textContent=text;
    document.querySelectorAll('.page').forEach(el=>{const active=el.id===`page-${page}`;el.hidden=!active;el.classList.toggle('active',active);});
    document.querySelectorAll('.nav-button').forEach(el=>{el.classList.toggle('active',el.dataset.page===page);if(el.dataset.page===page)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');el.title=copy[el.dataset.page][0];el.setAttribute('aria-label',copy[el.dataset.page][0]);});
    this.render();if(page==='operations')this.game.map?.resize();if(page==='multiplayer')this.refreshLobbies();window.scrollTo({top:0,behavior:'instant'});
  }
  selectCountry(id,focus=true){this.countryId=Utils.country(id)?id:null;document.getElementById('countrySelect').value=this.countryId||'';this.game.map?.select(this.countryId,focus);this.renderMapOffers();}
  render(){
    const focused=document.activeElement,focusData=focused?.dataset.action?{...focused.dataset}:null;
    this.renderMapOffers();this.renderActive('activeMissions');this.renderActive('contractsActive');
    if(this.page==='strategy')this.renderStrategy();if(this.page==='contracts')this.renderContracts();if(this.page==='fleet')this.renderFleet();if(this.page==='upgrades')this.renderUpgrades();if(this.page==='diplomacy')this.renderDiplomacy();if(this.page==='multiplayer')this.renderMultiplayer();if(this.page==='company')this.renderCompany();if(this.page==='log')this.renderLog();
    this.updateLive();
    if(focusData&&!document.contains(focused)){const buttons=Array.from(document.querySelectorAll('[data-action]'));const match=buttons.find(b=>Object.entries(focusData).every(([k,v])=>b.dataset[k]===v));if(match&&!match.disabled)match.focus({preventScroll:true});}
  }
  renderMapOffers(){
    const country=Utils.country(this.countryId);document.getElementById('regionTitle').textContent=country?.properties.name||'Worldwide';
    const offers=this.state.offers.filter(c=>!this.countryId||c.countryId===this.countryId).slice(0,3);
    document.getElementById('mapOffers').innerHTML=offers.length?offers.map(c=>{const t=CONFIG.contractTypes[c.typeIndex],q=contractSystem.quote(this.state,c);return `<button class="rail-card" data-action="offer" data-id="${c.id}"><span class="contract-icon">${icon(t.icon)}</span><div><h3>${Utils.escape(t.name)}</h3><p>${Utils.escape(Utils.country(c.countryId).properties.name)} · Class ${c.requiredQuality}</p><div class="rail-reward"><strong>+ ${Utils.money(q.reward-q.cost)}</strong><span>${Utils.time(q.duration)} MIN</span></div></div></button>`;}).join(''):`<p class="rail-empty">${country?'No contracts here yet. Search for new offers below.':'All offers are active. Find new contracts or complete a mission.'}</p>`;
  }
  renderContracts(){
    document.getElementById('contractsList').innerHTML=this.state.offers.length?this.state.offers.map(c=>{
      const t=CONFIG.contractTypes[c.typeIndex],q=contractSystem.quote(this.state,c);return `<article class="card"><div class="card-head"><span class="card-icon">${icon(t.icon)}</span><span class="badge">KLASSE ${c.requiredQuality}</span></div><h3>${Utils.escape(t.name)}</h3><p class="location">${Utils.escape(Utils.country(c.countryId).properties.name)} · ${t.client}</p><p class="description">${t.description}</p><div class="reward">${Utils.money(q.reward-q.cost)}</div><p class="reward-label">Contractwinst, exclusief vlootonderhoud</p><div class="card-stats"><div class="card-stat"><span>Startkosten</span><strong>${Utils.money(q.cost)}</strong></div><div class="card-stat"><span>Geschatte duur</span><strong>${Utils.time(q.duration)}</strong></div><div class="card-stat"><span>Reputatie / onderzoek</span><strong>+${c.reputation} / +${c.reputation*2}</strong></div></div><button class="outline-button full" data-action="offer" data-id="${c.id}">Bekijk contract ${icon('arrow')}</button></article>`;
    }).join(''):'<div class="empty-state"><div><h3>Alle contracten zijn aangenomen.</h3><p>Vernieuw het aanbod om meer opdrachten te vinden.</p></div></div>';
  }
  renderActive(id){
    const container=document.getElementById(id);container.innerHTML=this.state.activeContracts.length?this.state.activeContracts.map(c=>{
      const t=CONFIG.contractTypes[c.typeIndex],sat=this.state.satellites.find(s=>s.id===c.satelliteId);return `<article class="mission-row">${icon(t.icon)}<div><h3>${Utils.escape(t.name)}</h3><p>${Utils.escape(Utils.country(c.countryId).properties.name)} · ${Utils.escape(sat?.name||'Satelliet')}</p></div><div class="mission-progress"><div class="progress-meta"><span data-remaining="${c.id}"></span><span data-percent="${c.id}"></span></div><div class="progress" role="progressbar" aria-label="Voortgang ${Utils.escape(t.name)}" aria-valuemin="0" aria-valuemax="100" data-progress="${c.id}"><span></span></div></div><div class="mission-value">+${Utils.money(c.reward)}<small>bij voltooiing</small></div></article>`;
    }).join(''):`<div class="empty-state">${icon('radar')}<div><h3>Je volgende missie begint hier.</h3><p>Accepteer een contract om je satelliet aan het werk te zetten.</p></div><button class="outline-button" data-page="contracts">Kies een contract ${icon('arrow')}</button></div>`;
  }
  renderFleet(){
    const state=this.state;document.getElementById('fleetCount').textContent=`${state.satellites.length} satelliet${state.satellites.length===1?'':'en'} in een baan om de aarde`;
    document.getElementById('satellitesList').innerHTML=state.satellites.map(s=>{
      const stats=satelliteSystem.stats(state,s),busy=s.activeContract!==null;return `<article class="card"><div class="card-head"><span class="card-icon" style="color:${stats.color}">${icon('satellite')}</span><span class="badge ${busy?'green':''}">${busy?'IN OPERATIE':'BESCHIKBAAR'}</span></div><h3>${Utils.escape(s.name)}</h3><p class="location">Klasse ${stats.quality} · ${stats.role.toLowerCase()}</p><div class="card-stats"><div class="card-stat"><span>Conditie</span><strong data-health="${s.id}">${s.health.toFixed(1)}%</strong></div><div class="progress"><span data-health-bar="${s.id}" style="width:${s.health}%"></span></div><div class="card-stat"><span>Efficiëntie</span><strong>${Math.round(stats.efficiency*100)}%</strong></div><div class="card-stat"><span>Dekking</span><strong>${stats.coverage}%</strong></div><div class="card-stat"><span>Onderhoud / spelmaand</span><strong>${Utils.money(stats.maintenance)}</strong></div></div><div class="card-actions"><button class="outline-button" data-action="satellite" data-id="${s.id}">Details</button><button class="outline-button" data-action="repair" data-id="${s.id}">Repareer</button></div></article>`;
    }).join('');
    document.getElementById('shopList').innerHTML=Object.entries(CONFIG.satelliteTypes).map(([key,s])=>`<article class="card"><div class="hardware-header"><div style="color:${s.color}">${icon('satellite')}</div><div class="eyebrow">${s.role} / KLASSE ${s.quality}</div><h3>${s.name}</h3><p>${s.description}</p></div><div class="card-stats"><div class="card-stat"><span>Basisdekking</span><strong>${s.coverage}%</strong></div><div class="card-stat"><span>Basisefficiëntie</span><strong>${Math.round(s.efficiency*100)}%</strong></div><div class="card-stat"><span>Basisonderhoud / maand</span><strong>${Utils.money(s.maintenance)}</strong></div></div><div class="reward" style="color:${s.color}">${Utils.money(s.price)}</div><p class="reward-label">Aanschaf inclusief lancering</p><div class="card-actions"><button class="primary-button" data-action="buy" data-type="${key}" data-price="${s.price}">Koop & lanceer ${icon('arrow')}</button></div></article>`).join('');
  }
  renderStrategy(){
    const s=this.state,progress=strategySystem.progress(s),rows=strategySystem.scoreboard(s),objectives=strategySystem.objectiveTypes;
    document.getElementById('strategyOverview').innerHTML=`<div class="strategy-hero"><div><p class="eyebrow">VICTORY ROUTE</p><h2>${progress.objective.name}</h2><p>${progress.objective.description}</p><div class="progress"><span style="width:${progress.percent}%"></span></div><div class="progress-meta"><span>${Math.round(progress.value).toLocaleString('en-US')} current</span><span>${Math.round(progress.percent)}%</span></div></div><div class="objective-picker">${Object.entries(objectives).map(([id,o])=>`<button class="${s.strategy.objective===id?'selected':''}" data-orbital-action="objective" data-objective="${id}"><strong>${o.name}</strong><small>${o.description}</small></button>`).join('')}</div></div><div class="strategy-grid"><section class="panel command-panel"><div class="section-heading"><h2>Command actions</h2><span class="status-pill">DEFENSE ${Math.round(s.strategy.defense)}%</span></div><div class="command-actions"><button class="primary-button" data-orbital-action="build-relay">Deploy relay in selected country</button><button class="outline-button" data-orbital-action="defend">Raise defenses · €30k</button><button class="outline-button" data-page="diplomacy">Open diplomacy</button></div><p class="subtle">Select a country on the globe before deploying a relay. Taking a rival-controlled country replaces its network node.</p></section><section class="panel scoreboard-panel"><div class="section-heading"><h2>Live ranking</h2><span class="subtle">Updates every 15 seconds</span></div>${rows.map((r,i)=>`<div class="score-row"><span class="rank">${i+1}</span><i style="background:${r.color}"></i><strong>${Utils.escape(r.name)}</strong><span>${r.influence}% influence</span><span>${r.relays} relays</span><b>${r.score} pts</b></div>`).join('')}</section></div>`;
  }
  renderUpgrades(){
    strategySystem.ensure(this.state);const unlocked=this.state.strategy.unlocked;
    document.getElementById('researchTree').innerHTML=Object.entries(strategySystem.researchNodes).map(([branch,nodes])=>`<section class="research-branch"><h3>${branch.replace(/([A-Z])/g,' $1')}</h3><div>${nodes.map((n,i)=>{const done=unlocked.includes(n.id),available=i===0||unlocked.includes(nodes[i-1].id);return `<button class="research-node ${done?'done':''}" data-orbital-action="research" data-research-node="${n.id}" data-research="${n.cost}" ${done||!available?'disabled':''}><span>${done?'✓':i+1}</span><strong>${n.name}</strong><small>${n.text}</small><b>${done?'COMPLETE':`${n.cost} ◇`}</b></button>`;}).join('')}</div></section>`).join('');
    document.getElementById('upgradesList').innerHTML=Object.keys(CONFIG.upgradeTypes).map(key=>{
      const u=upgradeSystem.info(this.state,key);return `<article class="card"><div class="card-head"><span class="card-icon">${icon(u.icon)}</span><span class="badge">NIVEAU ${u.level} / ${u.max}</span></div><h3>${u.name}</h3><p class="description">${u.description}</p><div class="upgrade-levels">${Array.from({length:u.max},(_,i)=>`<span class="${i<u.level?'filled':''}"></span>`).join('')}</div><div class="card-stats"><div class="card-stat"><span>Investering</span><strong>${u.level===u.max?'Voltooid':Utils.money(u.cost)}</strong></div><div class="card-stat"><span>Onderzoekspunten</span><strong class="cyan">${u.level===u.max?'Voltooid':`${u.researchCost} ◇`}</strong></div></div><button class="${u.level===u.max?'outline-button':'primary-button'} full" data-action="upgrade" data-key="${key}" data-price="${u.cost}" data-research="${u.researchCost}" ${u.level===u.max?'data-maxed="true" disabled':''}>${u.level===u.max?'Maximaal ontwikkeld':'Ontwikkel verbetering'} ${icon(u.level===u.max?'check':'arrow')}</button></article>`;
    }).join('');
  }
  renderCompany(){
    const s=this.state,p=Utils.progress(s);document.getElementById('companyOverview').innerHTML=`<div class="company-hero"><p class="eyebrow">SPACE CORP / LEVEL ${s.level}</p><h2>${CONFIG.levelNames[s.level-1]}</h2><p>${s.level===5?'Je hebt de hoogste bedrijfsrang bereikt. Breid je vloot verder uit.':`Verdien nog ${Utils.money(p.remaining)} aan contractbeloningen voor level ${s.level+1}.`}</p><div class="progress"><span style="width:${p.percent}%"></span></div><div class="progress-meta"><span>${Utils.money(s.totalMoneyEarned)} totale omzet</span><span>${p.percent.toFixed(0)}%</span></div></div><div class="metrics-grid"><div class="metric"><div><span>Totale contractomzet</span><strong>${Utils.money(s.totalMoneyEarned)}</strong></div></div><div class="metric"><div><span>Totale uitgaven</span><strong id="totalCosts">${Utils.money(s.totalCosts)}</strong></div></div><div class="metric"><div><span>Contracten voltooid</span><strong>${s.completedContracts}</strong></div></div><div class="metric"><div><span>Speeltijd</span><strong id="companyPlayTime">${Utils.clock(s.playTime)}</strong></div></div></div><div class="section-heading"><h2>Laatste voltooide contracten</h2></div><div class="panel log-list">${s.history.length?s.history.slice(0,8).map(m=>`<div class="log-entry success"><time>${Utils.clock(m.time)}</time><span>${CONFIG.contractTypes[m.typeIndex].name} · ${Utils.escape(Utils.country(m.countryId).properties.name)} · ${Utils.money(m.profit)} winst</span></div>`).join(''):'<div class="log-entry"><span class="subtle">Voltooi je eerste contract om hier je resultaten te zien.</span></div>'}</div>`;
  }
  renderLog(){document.getElementById('logList').innerHTML=this.state.log.slice().reverse().map(l=>`<div class="log-entry ${l.type}"><time>${Utils.clock(l.time)}</time><span>${Utils.escape(l.message)}</span></div>`).join('')||'<div class="log-entry">Er zijn nog geen gebeurtenissen.</div>';}
  updateLive(){
    const s=this.state,p=Utils.progress(s),objective=strategySystem.progress(s);const set=(id,text)=>{const el=document.getElementById(id);if(el&&el.textContent!==String(text))el.textContent=text;};
    set('moneyDisplay',Utils.money(s.money));set('reputationDisplay',s.reputation);set('researchDisplay',s.research);set('missionClock',Utils.clock(s.playTime));set('activeCount',s.activeContracts.length);set('runningBadge',s.activeContracts.length);set('expectedProfit',Utils.money(s.activeContracts.reduce((sum,c)=>sum+c.reward-c.cost,0)));set('maintenanceDisplay',Utils.money(satelliteSystem.monthlyCost(s)));set('navOfferCount',s.offers.length);set('sidebarLevel',`Level ${s.level} · ${CONFIG.levelNames[s.level-1]}`);set('nextLevelHint',s.level===5?'Highest company level reached':`${Utils.money(p.remaining)} to level ${s.level+1}`);set('systemStatus',s.paused?'SIMULATION PAUSED':'SYSTEMS OPERATIONAL');set('companyPlayTime',Utils.clock(s.playTime));set('totalCosts',Utils.money(s.totalCosts));set('objectiveName',objective.objective.name);set('objectiveDescription',objective.objective.description);set('objectiveProgress',`${Math.round(objective.value).toLocaleString('en-US')} / ${objective.target.toLocaleString('en-US')}${objective.objective.unit}`);
    const objectiveBar=document.getElementById('objectiveBar');if(objectiveBar)objectiveBar.style.width=objective.percent+'%';const relayButton=document.getElementById('buildRelayButton');if(relayButton)relayButton.textContent=`Deploy ground relay · ${Utils.money(strategySystem.relayCost(s))}`;
    document.getElementById('sidebarProgress').style.width=p.percent+'%';document.getElementById('systemDot').style.background=s.paused?'var(--amber)':'var(--mint)';
    const free=satelliteSystem.available(s).length;document.getElementById('freeSatellites').innerHTML=`${free} <small>/ ${s.satellites.length}</small>`;
    const pause=document.getElementById('pauseButton');if(pause.dataset.paused!==String(s.paused)){pause.innerHTML=icon(s.paused?'play':'pause');pause.dataset.paused=s.paused;pause.setAttribute('aria-label',s.paused?'Resume game':'Pause game');pause.title=s.paused?'Resume':'Pause';}set('speedButton',s.speed+'×');
    for(const c of s.activeContracts){const progress=Utils.clamp(c.elapsed/c.duration*100,0,100);document.querySelectorAll(`[data-remaining="${c.id}"]`).forEach(el=>el.textContent=Utils.time(c.duration-c.elapsed)+' resterend');document.querySelectorAll(`[data-percent="${c.id}"]`).forEach(el=>el.textContent=progress.toFixed(0)+'%');document.querySelectorAll(`[data-progress="${c.id}"]`).forEach(el=>{el.firstElementChild.style.width=progress+'%';el.setAttribute('aria-valuenow',Math.floor(progress));});}
    document.querySelectorAll('[data-price]').forEach(el=>{el.disabled=Boolean(el.dataset.maxed)||s.money<Number(el.dataset.price)||s.research<Number(el.dataset.research||0);if(el.disabled&&!el.dataset.maxed)el.title=s.money<Number(el.dataset.price)?'Onvoldoende geld':'Onvoldoende onderzoekspunten';else el.title='';});
    document.querySelectorAll('[data-action="repair"]').forEach(el=>{const sat=s.satellites.find(v=>v.id===Number(el.dataset.id));if(!sat)return;const cost=satelliteSystem.repairCost(sat);el.textContent=`Repareer · ${Utils.money(cost)}`;el.disabled=sat.activeContract!==null||sat.health>=99.99||s.money<cost;el.title=sat.activeContract!==null?'Wacht tot het contract klaar is.':'';});
    document.querySelectorAll('[data-health]').forEach(el=>{const sat=s.satellites.find(v=>v.id===Number(el.dataset.health));if(sat)el.textContent=sat.health.toFixed(1)+'%';});document.querySelectorAll('[data-health-bar]').forEach(el=>{const sat=s.satellites.find(v=>v.id===Number(el.dataset.healthBar));if(sat)el.style.width=sat.health+'%';});
    if(this.openOffer&&this.dialog.open)this.updateQuote();
  }
  openDialog(title,body,eyebrow='MISSIEBRIEFING'){
    this.openOffer=null;document.getElementById('dialogTitle').textContent=title;document.getElementById('dialogEyebrow').textContent=eyebrow;document.getElementById('dialogBody').innerHTML=body;document.getElementById('dialogActions').replaceChildren();if(!this.dialog.open)this.dialog.showModal();
  }
  dialogButton(label,fn,primary=false){const b=document.createElement('button');b.className=primary?'primary-button':'outline-button';b.textContent=label;b.addEventListener('click',fn);document.getElementById('dialogActions').appendChild(b);return b;}
  showContract(id){
    const c=this.state.offers.find(v=>v.id===id);if(!c)return;const t=CONFIG.contractTypes[c.typeIndex],available=satelliteSystem.available(this.state,c.requiredQuality);
    this.openDialog(t.name,`<p>${Utils.escape(t.client)} · ${Utils.escape(Utils.country(c.countryId).properties.name)} · Klasse ${c.requiredQuality}</p><p style="margin-top:12px">${t.description}</p><div class="briefing"><div><span>Beloning na voltooiing</span><strong id="quoteReward" class="cyan"></strong></div><div><span>Startkosten</span><strong id="quoteCost"></strong></div><div><span>Contractwinst</span><strong id="quoteProfit" class="cyan"></strong></div><div><span>Duur in speltijd</span><strong id="quoteDuration"></strong></div></div><label class="field-label" for="satelliteChoice">Satelliet toewijzen</label><select id="satelliteChoice" ${available.length?'':'disabled'}>${available.length?available.map(s=>`<option value="${s.id}">${Utils.escape(s.name)} · ${Math.round(s.health)}% conditie</option>`).join(''):'<option>Geen geschikte satelliet beschikbaar</option>'}</select><p class="subtle" style="margin-top:12px">+${c.reputation} reputatie · +${c.reputation*2} onderzoekspunten. Startkosten worden direct betaald. Vlootonderhoud loopt apart door.</p><p id="quoteMessage" class="dialog-message"></p>`);
    this.openOffer=id;document.getElementById('satelliteChoice').addEventListener('change',()=>this.updateQuote());
    this.dialogButton('Sluiten',()=>this.dialog.close());const b=this.dialogButton('Start contract',()=>{const sid=Number(document.getElementById('satelliteChoice').value);if(this.game.accept(id,sid))this.dialog.close();},true);b.id='acceptContractButton';this.updateQuote();
  }
  updateQuote(){
    const c=this.state.offers.find(v=>v.id===this.openOffer),button=document.getElementById('acceptContractButton');if(!c||!button){if(button)button.disabled=true;return;}
    const selected=Number(document.getElementById('satelliteChoice').value);const sat=satelliteSystem.available(this.state,c.requiredQuality).find(s=>s.id===selected),q=contractSystem.quote(this.state,c,sat);
    for(const [id,value]of Object.entries({quoteReward:Utils.money(q.reward),quoteCost:Utils.money(q.cost),quoteProfit:Utils.money(q.reward-q.cost),quoteDuration:Utils.time(q.duration)}))document.getElementById(id).textContent=value;
    button.disabled=!sat||this.state.money<q.cost;document.getElementById('quoteMessage').textContent=!sat?'Je hebt een vrije satelliet nodig met de juiste klasse en voldoende conditie.':this.state.money<q.cost?'Je hebt onvoldoende geld voor de startkosten.':'';
  }
  showSatellite(id){const sat=this.state.satellites.find(s=>s.id===id);if(!sat)return;const stats=satelliteSystem.stats(this.state,sat);this.openDialog(sat.name,`<p>${stats.description}</p><div class="briefing"><div><span>Conditie</span><strong>${sat.health.toFixed(1)}%</strong></div><div><span>Efficiëntie</span><strong>${Math.round(stats.efficiency*100)}%</strong></div><div><span>Dekking</span><strong>${stats.coverage}%</strong></div><div><span>Onderhoud / spelmaand</span><strong>${Utils.money(stats.maintenance)}</strong></div><div><span>Tijd in de ruimte</span><strong>${Utils.clock(sat.age)}</strong></div><div><span>Status</span><strong>${sat.activeContract!==null?'In operatie':sat.health<=0?'Reparatie nodig':'Beschikbaar'}</strong></div></div><p>Een hogere efficiëntie verkort de duur van nieuwe contracten. Dekking en resolutie verhogen hun beloning. Repareer je satelliet wanneer de conditie afneemt.</p>`,'SATELLIETTELEMETRIE');this.dialogButton('Sluiten',()=>this.dialog.close());}
  showHelp(){this.openDialog('Je eerste missie.',`<ol class="help-list"><li>Je begint met <strong>€100.000 en één Scout-1</strong>. Kies een contract in het missiecentrum.</li><li>Wijs je satelliet toe en betaal de startkosten. Na ongeveer twee spelminuten ontvang je de beloning.</li><li>Koop extra satellieten om meerdere opdrachten tegelijk uit te voeren.</li><li>Verdien onderzoekspunten met contracten. Verbeter je vloot onder Onderzoek.</li><li>Sleep de aardbol, klik op landen of gebruik de landkeuze. Zoek contracten voor je gekozen land.</li></ol><p>Met 3× versnel je de simulatie. Pauzeren of het tabblad verbergen stopt de speeltijd. Een spelmaand duurt 30 spelminuten. Je voortgang blijft in deze browser bewaard.</p>`,'SNEL AAN DE SLAG');this.dialogButton('Begrepen',()=>this.dialog.close(),true);}
  confirmNewGame(){this.openDialog('Opnieuw beginnen?',`<p>Hiermee vervang je je huidige bedrijf, satellieten en voortgang door een nieuw spel met €100.000 en één Scout-1.</p>`,'NIEUW SPEL');this.dialogButton('Terug',()=>this.dialog.close());const b=this.dialogButton('Begin opnieuw',()=>{this.dialog.close();this.game.newGame();});b.className='danger-button';}
  initOrbitalPact(){
    this.profile=identitySystem.load();this.updateProfileUI();
    const launch=document.getElementById('launchScreen'),setup=document.getElementById('setupDialog'),profileDialog=document.getElementById('profileDialog');
    const close=id=>document.getElementById(id)?.addEventListener('click',()=>document.getElementById(id.replace('close','').replace('Close','').toLowerCase())?.close?.());
    document.getElementById('closeSetup').addEventListener('click',()=>setup.close());document.getElementById('closeProfile').addEventListener('click',()=>profileDialog.close());
    document.getElementById('soloButton').addEventListener('click',()=>this.showSoloSetup());document.getElementById('multiButton').addEventListener('click',()=>{launch.hidden=true;this.navigate('multiplayer');});document.getElementById('continueButton').addEventListener('click',()=>{launch.hidden=true;this.navigate('operations');});
    document.getElementById('profileButton').addEventListener('click',()=>this.showProfile());document.getElementById('quickJoinButton').addEventListener('click',()=>this.quickJoin());document.getElementById('createLobbyButton').addEventListener('click',()=>this.showLobbySetup());
    document.addEventListener('click',e=>{const b=e.target.closest('[data-orbital-action]');if(!b||b.disabled)return;const id=b.dataset.rival;switch(b.dataset.orbitalAction){case'ally':this.game.alliance(id);break;case'break':this.game.breakAlliance(id);break;case'donate':this.game.donate(id,10000);break;case'joint':this.game.jointProject(id);break;case'sabotage':this.game.sabotage(id,b.dataset.operation||'cyber');break;case'join-lobby':this.joinLobby(b.dataset.lobby);break;case'refresh-lobbies':this.refreshLobbies();break;case'build-relay':this.game.buildRelay(this.countryId);break;case'defend':this.game.defend();break;case'research':this.game.researchNode(b.dataset.researchNode);break;case'objective':this.game.setObjective(b.dataset.objective);break;}this.render();});
    document.getElementById('backendStatus').textContent=backend.configured()?'Live services configured':'Development build · solo available; online integration unfinished';
    this.liveLobbies=[];this.onlineError='';
    if(this.state.playTime>1000)document.getElementById('continueButton').hidden=false;
  }
  updateProfileUI(){const p=this.profile||identitySystem.load(),initial=p.name.slice(0,2).toUpperCase();document.getElementById('profileName').textContent=p.name;document.getElementById('profileAvatar').textContent=initial;document.getElementById('profileType').textContent=p.guest?'Guest profile':p.localOnly?'Local profile':'Account';}
  showProfile(){const d=document.getElementById('profileDialog');document.getElementById('profileBody').innerHTML=`<p>Your current identity is <strong>${Utils.escape(this.profile.name)}</strong>. Guests automatically receive an Anon#### name.</p><label class="field-label" for="profileNameInput">Display name</label><input id="profileNameInput" class="text-input" maxlength="20" value="${Utils.escape(this.profile.guest?'':this.profile.name)}" placeholder="Commander name"><div class="profile-actions"><button id="saveProfileName" class="primary-button">${this.profile.guest?'Create local profile':'Save name'}</button><button id="useGuest" class="outline-button">Use guest identity</button></div><p class="subtle">A production account can be linked to Supabase Auth. This preview stores the profile locally.</p>`;d.showModal();document.getElementById('saveProfileName').onclick=()=>{const value=document.getElementById('profileNameInput').value,r=this.profile.guest?identitySystem.localAccount(this.profile,value):identitySystem.rename(this.profile,value);if(r.error)return this.toast(r.error,true);this.profile=r.profile;this.updateProfileUI();d.close();};document.getElementById('useGuest').onclick=()=>{try{localStorage.removeItem(identitySystem.key)}catch(e){}this.profile=identitySystem.anon();this.updateProfileUI();d.close();};}
  showSoloSetup(){const d=document.getElementById('setupDialog');document.getElementById('setupEyebrow').textContent='SOLO SETUP';document.getElementById('setupTitle').textContent='New solo campaign';document.getElementById('setupBody').innerHTML=`<div class="setup-grid"><label>Difficulty<select id="soloDifficulty"><option value="easy">Easy, €150k start</option><option value="normal" selected>Normal, €100k start</option><option value="hard">Hard, €75k start</option><option value="expert">Expert, €50k start</option></select></label><label>Pace<select id="soloPace"><option value="slow">Slow</option><option value="standard" selected>Standard</option><option value="fast">Fast</option></select></label><label>Victory condition<select id="soloObjective"><option value="influence">60% orbital influence</option><option value="economy">€2M company value</option><option value="network">18 ground relays</option><option value="score">1,000 Pact Score</option></select></label></div><div class="toggle-list"><label><input id="soloEndless" type="checkbox" checked> Endless campaign (no automatic victory)</label><label><input id="soloFog" type="checkbox" checked> Fog of intelligence</label><label><input id="soloAlliances" type="checkbox" checked> Alliances enabled</label><label><input id="soloSabotage" type="checkbox" checked> Strategic operations enabled</label></div><p class="subtle">Solo has no forced timer. Rival corporations keep expanding while you play.</p>`;const actions=document.getElementById('setupActions');actions.innerHTML='<button class="outline-button" id="cancelSolo">Cancel</button><button class="primary-button" id="startSolo">Start campaign</button>';document.getElementById('cancelSolo').onclick=()=>d.close();document.getElementById('startSolo').onclick=()=>{this.game.newGame({mode:'solo',difficulty:document.getElementById('soloDifficulty').value,settings:{endless:document.getElementById('soloEndless').checked,pace:document.getElementById('soloPace').value,objective:document.getElementById('soloObjective').value,fog:document.getElementById('soloFog').checked,alliances:document.getElementById('soloAlliances').checked,sabotage:document.getElementById('soloSabotage').checked}});d.close();document.getElementById('launchScreen').hidden=true;this.navigate('operations');};d.showModal();}
  showLobbySetup(){const d=document.getElementById('setupDialog');document.getElementById('setupEyebrow').textContent='CREATE LOBBY';document.getElementById('setupTitle').textContent='Host an orbital sector';document.getElementById('setupBody').innerHTML=`<div class="setup-grid"><label>Difficulty<select id="lobbyDifficulty"><option>easy</option><option selected>normal</option><option>hard</option><option>expert</option></select></label><label>Max players<select id="lobbyPlayers"><option>2</option><option>4</option><option selected>6</option><option>8</option><option>12</option></select></label><label>Game pace<select id="lobbyPace"><option>slow</option><option selected>standard</option><option>fast</option></select></label><label>Starting funds<select id="lobbyMoney"><option value="50000">€50,000</option><option value="100000" selected>€100,000</option><option value="150000">€150,000</option></select></label><label>Victory condition<select id="lobbyObjective"><option value="influence">60% influence</option><option value="economy">€2M company value</option><option value="network">18 relays</option><option value="score">1,000 Pact Score</option></select></label></div><div class="toggle-list"><label><input id="lobbyFog" type="checkbox" checked> Fog of intelligence</label><label><input id="lobbyAlliances" type="checkbox" checked> Alliances</label><label><input id="lobbySabotage" type="checkbox" checked> Strategic operations</label></div>`;document.getElementById('setupActions').innerHTML='<button class="outline-button" id="cancelLobby">Cancel</button><button class="primary-button" id="hostLobby">Create public lobby</button>';document.getElementById('cancelLobby').onclick=()=>d.close();document.getElementById('hostLobby').onclick=async()=>{const settings={difficulty:document.getElementById('lobbyDifficulty').value,maxPlayers:+document.getElementById('lobbyPlayers').value,pace:document.getElementById('lobbyPace').value,startMoney:+document.getElementById('lobbyMoney').value,objective:document.getElementById('lobbyObjective').value,fog:document.getElementById('lobbyFog').checked,alliances:document.getElementById('lobbyAlliances').checked,sabotage:document.getElementById('lobbySabotage').checked};const button=document.getElementById('hostLobby');button.disabled=true;button.textContent='Creating…';try{let lobby;if(onlineSystem.enabled()){const row=await onlineSystem.createLobby(this.profile,settings);lobby={id:row.id,name:row.name,host:row.host_name||this.profile.name,players:1,maxPlayers:row.max_players,...settings,online:true};}else lobby=multiplayerSystem.create(this.profile,settings);d.close();this.currentLobby=lobby;this.enterLobby(lobby);this.toast(lobby.online?'Live lobby created.':'Offline practice lobby created.');}catch(error){this.toast(error.message,true);button.disabled=false;button.textContent='Create public lobby';}};d.showModal();}
  renderMultiplayer(){const lobbies=[...(this.liveLobbies||[]),...multiplayerSystem.load().filter(x=>!this.liveLobbies?.some(y=>y.id===x.id))],mode=onlineSystem.enabled()?'LIVE NETWORK':'OFFLINE PRACTICE';document.getElementById('lobbyList').innerHTML=`<div class="network-status"><span class="live-dot"></span><strong>${mode}</strong><span>${this.onlineError||`${lobbies.length} sectors available`}</span><button class="text-button" data-orbital-action="refresh-lobbies">Refresh</button></div>`+(lobbies.map(l=>`<article class="lobby-row"><div class="lobby-signal"><span class="live-dot"></span></div><div><strong>${Utils.escape(l.name)}</strong><p>Host ${Utils.escape(l.host)} · ${multiplayerSystem.difficultyLabel(l.difficulty)} · ${Utils.escape(l.pace||'standard')} ${l.online?'· LIVE':'· PRACTICE'}</p></div><div class="lobby-players">${l.players}/${l.maxPlayers}<small>PLAYERS</small></div><div class="lobby-tags"><span>${l.alliances===false?'No alliances':'Alliances'}</span><span>${l.sabotage===false?'No operations':'Operations'}</span><span>${Utils.escape(l.objective||'influence')}</span></div><button class="outline-button" data-orbital-action="join-lobby" data-lobby="${l.id}" ${l.players>=l.maxPlayers?'disabled':''}>Join</button></article>`).join('')||'<div class="empty-state"><div><h3>No public lobbies found</h3><p>Create the first sector.</p></div></div>');}
  async refreshLobbies(){if(!onlineSystem.enabled()){this.liveLobbies=[];this.onlineError='Supabase is not configured. Practice lobbies still work.';if(this.page==='multiplayer')this.renderMultiplayer();return;}try{this.liveLobbies=await onlineSystem.lobbies();this.onlineError='';}catch(error){this.onlineError=error.message;}if(this.page==='multiplayer')this.renderMultiplayer();}
  async quickJoin(){const live=(this.liveLobbies||[]).filter(l=>l.players<l.maxPlayers).sort((a,b)=>b.players-a.players)[0];if(live)return this.joinLobby(live.id);const lobby=multiplayerSystem.quickJoin(this.profile);if(!lobby)return this.toast('No open lobby found.',true);this.enterLobby(lobby);}
  async joinLobby(id){let lobby=(this.liveLobbies||[]).find(l=>l.id===id)||multiplayerSystem.load().find(l=>l.id===id);if(!lobby)return this.toast('Lobby is no longer available.',true);try{lobby=lobby.online?await onlineSystem.joinLobby(lobby,this.profile):multiplayerSystem.join(lobby,this.profile);this.enterLobby(lobby);}catch(error){this.toast(error.message,true);}}
  enterLobby(lobby){this.currentLobby=lobby;this.game.newGame({mode:'multiplayer',difficulty:lobby.difficulty,settings:{pace:lobby.pace,objective:lobby.objective||'influence',fog:lobby.fog!==false,alliances:lobby.alliances!==false,sabotage:lobby.sabotage!==false,startMoney:lobby.startMoney}});try{localStorage.setItem('orbitalPact_session_v1',JSON.stringify({lobbyId:lobby.id,lobbyName:lobby.name,host:lobby.host,joinedAt:Date.now(),online:Boolean(lobby.online)}));}catch(e){}if(lobby.online){onlineSystem.connect(lobby.id,this.profile);onlineSystem.on(msg=>this.handleNetworkMessage(msg));}this.openDialog(lobby.name,`<p>You joined a ${Utils.escape(multiplayerSystem.difficultyLabel(lobby.difficulty))} sector hosted by ${Utils.escape(lobby.host)}.</p><div class="briefing"><div><span>Players</span><strong>${lobby.players}/${lobby.maxPlayers}</strong></div><div><span>Pace</span><strong>${Utils.escape(lobby.pace||'standard')}</strong></div><div><span>Victory</span><strong>${Utils.escape(strategySystem.objectiveTypes[lobby.objective||'influence'].name)}</strong></div><div><span>Connection</span><strong>${lobby.online?'Live server':'Offline practice'}</strong></div></div><p class="subtle">Your session is stored for reconnect. The match server validates live actions when configured.</p>`,'SECTOR READY');this.dialogButton('Enter sector',()=>{this.dialog.close();this.navigate('operations');},true);}
  handleNetworkMessage(msg){if(msg.type==='presence')this.toast(`${msg.players} commanders connected.`);if(msg.type==='event'&&msg.message){this.game.log(msg.message);this.game.changed();}if(msg.type==='state'&&msg.scoreboard)this.remoteScoreboard=msg.scoreboard;}
  renderDiplomacy(){diplomacySystem.ensure(this.state);document.getElementById('diplomacyList').innerHTML=diplomacySystem.rivals.map(r=>{const rel=this.state.diplomacy.relations[r.id],allied=rel.status==='allied',cool=Math.max(0,(this.state.diplomacy.cooldowns[r.id]||0)-this.state.playTime);return `<article class="diplomacy-card ${allied?'allied':''}"><div class="diplomacy-head"><div class="corp-emblem" style="color:${strategySystem.colors[r.id]}">${r.name.slice(0,2).toUpperCase()}</div><div><h3>${r.name}</h3><p>${r.specialty} · Power ${r.power}</p></div><span class="status-pill">${allied?'ALLIED':'RIVAL'}</span></div><div class="trust-row"><span>Trust</span><div class="progress"><span style="width:${rel.trust}%"></span></div><strong>${rel.trust}</strong></div><p class="subtle">Support sent: ${Utils.money(rel.donated||0)}${rel.jointProject?' · Joint project active':''}</p><div class="diplomacy-actions">${allied?`<button class="primary-button" data-orbital-action="donate" data-rival="${r.id}">Donate €10k</button><button class="outline-button" data-orbital-action="joint" data-rival="${r.id}" ${rel.jointProject?'disabled':''}>Joint project</button><button class="outline-button" data-orbital-action="break" data-rival="${r.id}">End pact</button>`:`<button class="outline-button" data-orbital-action="ally" data-rival="${r.id}" ${this.state.matchSettings?.alliances===false?'disabled':''}>Propose pact</button><button class="danger-button" data-orbital-action="sabotage" data-operation="cyber" data-rival="${r.id}" ${this.state.matchSettings?.sabotage===false||cool>0?'disabled':''}>Cyber · €18k</button><button class="danger-button" data-orbital-action="sabotage" data-operation="jam" data-rival="${r.id}" ${this.state.matchSettings?.sabotage===false||cool>0?'disabled':''}>Jam · €30k</button>`}</div>${cool>0?`<p class="cooldown">Operations cooldown: ${Utils.time(cool)}</p>`:''}</article>`}).join('');}
  showEnd(ending){const dialog=document.getElementById('endDialog'),rows=strategySystem.scoreboard(this.state),winner=rows.find(r=>r.id===ending.winner);document.getElementById('endTitle').textContent=ending.winner==='player'?'Orbital victory':`${winner?.name||'A rival'} wins`;document.getElementById('endSummary').textContent=`${ending.objective.name} decided the match after ${Utils.clock(this.state.playTime)}.`;document.getElementById('endScoreboard').innerHTML=rows.map((r,i)=>`<div class="score-row"><span>${i+1}</span><i style="background:${r.color}"></i><strong>${Utils.escape(r.name)}</strong><span>${r.score} pts</span></div>`).join('');if(!dialog.open)dialog.showModal();}
  toast(message,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;const holder=document.getElementById('toasts');holder.appendChild(el);while(holder.children.length>3)holder.firstChild.remove();setTimeout(()=>el.remove(),5000);}
}
